"use strict";

// Exact n=8 screen for one one-noncoordinate rank-two star together with one
// or two arbitrary diagonal-anchor high-rank edges in the remainder factor.

const n=8,V=[0,1,2,3,4,5,6,7],R=[[0,1],[2,3],[4,5],[6,7]];
function edge(a,b){return a<b?[a,b]:[b,a];}function ek(a,b){return a<b?`${a},${b}`:`${b},${a}`;}function mk(M){return M.map(e=>e.join("")).join("|");}function tk(T){return T.map(mk).join(";");}
function pms(v){if(!v.length)return[[]];const a=v[0],out=[];for(let i=1;i<v.length;++i)for(const m of pms(v.slice(1,i).concat(v.slice(i+1))))out.push([edge(a,v[i]),...m].sort((x,y)=>x[0]-y[0]||x[1]-y[1]));return out;}
function dis(A,B){const s=new Set(A.map(e=>ek(...e)));return B.every(e=>!s.has(ek(...e)));}function con(E){const A=Array.from({length:n},()=>[]);for(const[a,b]of E){A[a].push(b);A[b].push(a);}const seen=new Set([0]),todo=[0];while(todo.length){const a=todo.pop();for(const b of A[a])if(!seen.has(b)){seen.add(b);todo.push(b);}}return seen.size===n;}
function perms(a){if(!a.length)return[[]];const out=[];for(let i=0;i<a.length;++i)for(const t of perms(a.slice(0,i).concat(a.slice(i+1))))out.push([a[i],...t]);return out;}function maps(){const out=[];for(const p of perms([0,1,2,3]))for(let f=0;f<16;++f){const m=Array(n);for(let i=0;i<4;++i)for(let s=0;s<2;++s)m[2*i+s]=2*p[i]+(s^((f>>>i)&1));out.push(m);}return out;}function trans(T,m,p){const U=Array(3);for(let q=0;q<3;++q)U[p[q]]=T[q].map(([a,b])=>edge(m[a],m[b])).sort((x,y)=>x[0]-y[0]||x[1]-y[1]);return U;}
function factorOrbits(){const all=pms(V),allow=all.filter(m=>dis(m,R)),S=new Map();for(const a of allow)for(const b of allow)if(dis(a,b))for(const c of allow)if(dis(a,c)&&dis(b,c)&&con([...R,...a,...b,...c])){const T=[a,b,c];S.set(tk(T),T);}const labelled=S.size,ms=maps(),ps=perms([0,1,2]),reps=[];while(S.size){const k=[...S.keys()].sort()[0],T=S.get(k);reps.push(T);for(const m of ms)for(const p of ps)S.delete(tk(trans(T,m,p)));}return{labelled,reps};}
function profiles(a){const o=[0,1,2].filter(x=>x!==a);return[[a,o[0]],[a,o[1]],[0,1,2]];}function partner(M,v){const e=M.find(x=>x.includes(v));return e[0]===v?e[1]:e[0];}function edgeIndex(M,v){return M.findIndex(e=>e.includes(v));}
function bit(i,j){return 1<<(3*i+j);}function orientedMask(root,pairs,e){let m=0;for(const[i,j]of pairs){const[a,b]=e[0]===root?[i,j]:[j,i];m|=bit(a,b);}return m;}function rectangle(root,P,Q,e,omit){const z=[];for(const i of P)for(const j of Q)if(!omit||i!==omit[0]||j!==omit[1])z.push([i,j]);return orientedMask(root,z,e);}
function descriptors(T){const out=[],a=0,Ps=profiles(a);for(let i=0;i<4;++i){const mEdge=T[a][i],[x,y]=mEdge,ri=edgeIndex(R,x),ti=edgeIndex(R,y);for(const P of Ps)for(const Q of Ps)out.push({kind:"SM",roots:[x,y],leaves:[partner(R,x),partner(R,y)],set:[[i,rectangle(x,P,Q,mEdge,null)],[12+ri,orientedMask(x,P.map(z=>[z,a]),R[ri])],[12+ti,orientedMask(y,Q.map(z=>[z,a]),R[ti])]]});const rEdge=R[i],[r,t]=rEdge,mi=edgeIndex(T[a],r),mj=edgeIndex(T[a],t);for(const P of Ps)for(const Q of Ps)out.push({kind:"SR",roots:[r,t],leaves:[partner(T[a],r),partner(T[a],t)],set:[[12+i,rectangle(r,P,Q,rEdge,[a,a])],[mi,orientedMask(r,P.map(z=>[z,a]),T[a][mi])],[mj,orientedMask(t,Q.map(z=>[z,a]),T[a][mj])]]});for(const[r0,t0]of[[x,y],[y,x]]){const rj=edgeIndex(R,r0),tj=edgeIndex(R,t0);for(const P of Ps)for(const b of[1,2])out.push({kind:"A",roots:[r0,t0],leaves:[partner(R,r0)],set:[[i,orientedMask(r0,[[a,a],...P.map(z=>[z,b])],mEdge)],[12+rj,orientedMask(r0,P.map(z=>[z,a]),R[rj])],[12+tj,orientedMask(t0,[[b,a]],R[tj])]]});}}return out;}
function graphPms(edges){const A=Array.from({length:n},()=>[]),out=[];for(let i=0;i<edges.length;++i){const[a,b]=edges[i];A[a].push([b,i]);A[b].push([a,i]);}function rec(S,M){if(!S.size){out.push(M.slice());return;}const a=Math.min(...S);for(const[b,i]of A[a])if(S.has(b)){const U=new Set(S);U.delete(a);U.delete(b);M.push(i);rec(U,M);M.pop();}}rec(new Set(V),[]);return out;}
function constraints(edges,pm,supports,D){const counts=new Map(),dpos=new Map(D.map((x,i)=>[x,i])),all=[];for(let a=0;a<3;++a)for(let b=0;b<3;++b)all.push([a,b]);for(const M of pm){let subset=0;for(const i of M)if(dpos.has(i))subset|=1<<dpos.get(i);const c=Array(n).fill(-1);function rec(j){if(j===M.length){const k=c.join(""),z=counts.get(k)||Array(1<<D.length).fill(0);++z[subset];counts.set(k,z);return;}const i=M[j],[a,b]=edges[i],mask=supports[i],S=dpos.has(i)?all:null;if(S){for(const[p,q]of S){c[a]=p;c[b]=q;rec(j+1);}}else for(let p=0;p<3;++p)for(let q=0;q<3;++q)if((mask>>>(3*p+q))&1){c[a]=p;c[b]=q;rec(j+1);}c[a]=c[b]=-1;}rec(0);}const out=[];for(const[k,z]of counts){if(new Set(k).size===1)continue;const bits=D.map(i=>{const[a,b]=edges[i];return bit(k.charCodeAt(a)-48,k.charCodeAt(b)-48);});out.push({bits,z});}return out;}
function highRank(mask){for(let a=0;a<3;++a)for(let b=a+1;b<3;++b)for(let c=0;c<3;++c)for(let d=c+1;d<3;++d)if((((mask>>>(3*a+c))&1)&&((mask>>>(3*b+d))&1))||(((mask>>>(3*a+d))&1)&&((mask>>>(3*b+c))&1)))return true;return false;}
const masks=Array.from({length:512},(_,i)=>i).filter(highRank),ALL=(1n<<BigInt(masks.length))-1n,contain=Array(9).fill(0n);for(let i=0;i<masks.length;++i)for(let b=0;b<9;++b)if(masks[i]&(1<<b))contain[b]|=1n<<BigInt(i);
function popcount(x){let z=0;while(x){x&=x-1n;++z;}return z;}function screenOne(C){let include=0,exclude=0;for(const{bits,z}of C){if(z[0]===1)include|=bits[0];if(z[0]+z[1]===1)exclude|=bits[0];}let out=0;for(const m of masks)if((m&include)===include&&(m&exclude)===0)++out;return out;}
function screenTwo(C){let out=0;for(const A of masks){let allow=ALL;for(const{bits,z}of C){const x=(A&bits[0])?1:0,c0=z[0]+x*z[1],c1=c0+z[2]+x*z[3],b=Math.log2(bits[1])|0,f0=c0===1,f1=c1===1;if(f0&&f1){allow=0n;break;}if(f0)allow&=contain[b];if(f1)allow&=ALL^contain[b];if(!allow)break;}out+=popcount(allow);}return out;}
function subsets(a,k){const out=[];function rec(i,z){if(z.length===k){out.push(z.slice());return;}for(let j=i;j<a.length;++j){z.push(a[j]);rec(j+1,z);z.pop();}}rec(0,[]);return out;}
const started=Date.now(),{labelled,reps}=factorOrbits(),stats={factor_orbits:reps.length,labelled_factor_triples:labelled,rank_at_least_two_masks:masks.length,by_size:{1:{structures:0,unit_labelings:0,support_tuples:0,survivors:0},2:{structures:0,unit_labelings:0,support_tuples:0,survivors:0}}},examples=[];
for(let oi=0;oi<reps.length;++oi){const T=reps[oi],edges=[...T[0],...T[1],...T[2],...R],pm=graphPms(edges);for(const A of descriptors(T)){const fixed=new Map();let conflict=false;for(const[i,m]of A.set){if(fixed.has(i)&&fixed.get(i)!==m)conflict=true;fixed.set(i,m);}if(conflict)continue;const blocked=new Set([...A.roots,...A.leaves]),candidates=[];for(let i=0;i<4;++i)if(!fixed.has(12+i)&&R[i].every(v=>!blocked.has(v)))candidates.push(12+i);for(let size=1;size<=Math.min(2,candidates.length);++size)for(const D of subsets(candidates,size)){const S=stats.by_size[size];++S.structures;const supports=Array(16).fill(0);for(let q=0;q<3;++q)for(let i=0;i<4;++i)supports[3*q+i]=bit(q,q);for(const[i,m]of fixed)supports[i]=m;const free=[];for(let i=12;i<16;++i)if(!fixed.has(i)&&!D.includes(i))free.push(i);for(let z=0;z<9**free.length;++z){let x=z;for(const i of free){const a=x%3;x=Math.floor(x/3);const b=x%3;x=Math.floor(x/3);supports[i]=bit(a,b);}++S.unit_labelings;const C=constraints(edges,pm,supports,D),survive=size===1?screenOne(C):screenTwo(C);S.support_tuples+=masks.length**size;S.survivors+=survive;if(survive&&examples.length<20)examples.push({orbit:oi,kind:A.kind,A,D,free,supports:supports.slice(),survive,perfect_matchings:pm.length});}}}}
if(masks.length!==478)throw new Error("mask census mismatch");
const result={stats,examples,elapsed_seconds:(Date.now()-started)/1000};
if(require.main===module)console.log(JSON.stringify(result,null,2));
module.exports=result;
