"use strict";

// Exact n=8 support screen for a reciprocal two-anchor rank-two star and the
// only possible second high-rank edge, between the two vertices outside the
// star.  The second edge ranges over every 3x3 support of matching number >=2.

const n=8,R=6,T=7,inside=[0,1,2,3,4,5],pairs=[];
for(let a=0;a<6;++a)for(let b=a+1;b<6;++b)pairs.push([a,b]);
function orderedDistinct(k){const out=[];function rec(a){if(a.length===k){out.push(a.slice());return;}for(const v of inside)if(!a.includes(v)){a.push(v);rec(a);a.pop();}}rec([]);return out;}
const graphs=new Map();for(let mask=0;mask<1<<15;++mask){const d=Array(6).fill(0),E=[];for(let i=0;i<15;++i)if((mask>>>i)&1){const[a,b]=pairs[i];++d[a];++d[b];E.push([a,b]);}const k=d.join("");if(!graphs.has(k))graphs.set(k,[]);graphs.get(k).push(E);}
function fourConnected(E,u){const A=Array.from({length:n},()=>[]);function add(a,b){A[a].push(b);A[b].push(a);}for(const e of E)add(...e);add(R,T);add(R,0);add(R,1);add(R,2);for(const v of u)add(T,v);for(let mask=0;mask<1<<n;++mask){let bits=0,start=-1,left=0;for(let v=0;v<n;++v){bits+=(mask>>>v)&1;if(!((mask>>>v)&1)){++left;if(start<0)start=v;}}if(bits>3)continue;const seen=new Set([start]),todo=[start];while(todo.length){const a=todo.pop();for(const b of A[a])if(!((mask>>>b)&1)&&!seen.has(b)){seen.add(b);todo.push(b);}}if(seen.size!==left)return false;}return true;}
function graphPms(E){const A=Array.from({length:n},()=>[]),out=[];for(let i=0;i<E.length;++i){const[a,b]=E[i];A[a].push([b,i]);A[b].push([a,i]);}function rec(S,M){if(!S.size){out.push(M.slice());return;}const a=Math.min(...S);for(const[b,i]of A[a])if(S.has(b)){const U=new Set(S);U.delete(a);U.delete(b);M.push(i);rec(U,M);M.pop();}}rec(new Set(Array.from({length:n},(_,i)=>i)),[]);return out;}
function permutations(a){if(!a.length)return[[]];const out=[];for(let i=0;i<a.length;++i)for(const t of permutations(a.slice(0,i).concat(a.slice(i+1))))out.push([a[i],...t]);return out;}
function colourings(E,u,variable){const leaves=[0,1,u[0],u[1]],inc=Array.from({length:6},()=>[]);for(let i=0;i<E.length;++i)for(const v of E[i])inc[v].push(i);const fixed=Array(E.length).fill(null),out=[];fixed[variable]=[-1,-1];function recLeaf(pos){if(pos===leaves.length){const free=[];for(let i=0;i<E.length;++i)if(fixed[i]===null)free.push(i);function recFree(j){if(j===free.length){out.push(fixed.map(x=>x.slice()));return;}for(let a=0;a<3;++a)for(let b=0;b<3;++b){fixed[free[j]]=[a,b];recFree(j+1);}fixed[free[j]]=null;}recFree(0);return;}const v=leaves[pos],hasUnitBoundary=(v===2||v===u[2]),need=hasUnitBoundary?[0,1]:[0,1,2],edges=inc[v];if(edges.length!==need.length)throw new Error("leaf degree mismatch");for(const p of permutations(need)){let ok=true;const changed=[];for(let j=0;j<edges.length;++j){const i=edges[j];if(i===variable)throw new Error("variable edge meets dense leaf");if(fixed[i]&&fixed[i][0]!==p[j]){ok=false;break;}if(!fixed[i]){fixed[i]=[p[j],p[j]];changed.push(i);}}if(ok)recLeaf(pos+1);for(const i of changed)fixed[i]=null;}}recLeaf(0);return out;}
function highRank(mask){for(let a=0;a<3;++a)for(let b=a+1;b<3;++b)for(let c=0;c<3;++c)for(let d=c+1;d<3;++d)if((((mask>>>(3*a+c))&1)&&((mask>>>(3*b+d))&1))||(((mask>>>(3*a+d))&1)&&((mask>>>(3*b+c))&1)))return true;return false;}
const masks=Array.from({length:512},(_,i)=>i).filter(highRank),allPairs=[];for(let a=0;a<3;++a)for(let b=0;b<3;++b)allPairs.push([a,b]);
function fixedSupport(i,labels){if(i===0)return[[0,0],[0,1],[1,0],[1,1]];if(i===1)return[[0,0],[1,0]];if(i===2)return[[0,1],[1,1]];if(i===3)return[[2,2]];if(i===4)return[[0,0],[1,0]];if(i===5)return[[0,1],[1,1]];if(i===6)return[[2,2]];return[labels[i-7]];}
function constraints(E,u,labels,variable){const full=[[R,T],[R,0],[R,1],[R,2],[T,u[0]],[T,u[1]],[T,u[2]],...E],dIndex=7+variable,[x,y]=E[variable],pm=graphPms(full),counts=new Map();for(const M of pm){const uses=M.includes(dIndex),c=Array(n).fill(-1);function rec(j){if(j===M.length){const k=c.join(""),z=counts.get(k)||[0,0];++z[uses?1:0];counts.set(k,z);return;}const i=M[j],[a,b]=full[i],S=i===dIndex?allPairs:fixedSupport(i,labels);for(const[p,q]of S){c[a]=p;c[b]=q;rec(j+1);}c[a]=c[b]=-1;}rec(0);}let include=0,exclude=0,mixedKeys=0;for(const[k,[c0,c1]]of counts){if(new Set(k).size===1)continue;++mixedKeys;const bit=1<<(3*(k.charCodeAt(x)-48)+(k.charCodeAt(y)-48));if(c0===1)include|=bit;if(c0+c1===1)exclude|=bit;}let survivors=0;for(const m of masks)if((m&include)===include&&(m&exclude)===0)++survivors;return{survivors,include,exclude,mixedKeys,perfect_matchings:pm.length};}
const started=Date.now(),stats={right_assignments:0,dense_leaf_distinct:0,degree_graphs:0,four_connected_graphs:0,graphs_with_extra_edge:0,base_labelings:0,total_support_masks:0,surviving_support_masks:0,base_cases_with_survivor:0},examples=[];
for(const u of orderedDistinct(3)){++stats.right_assignments;if(new Set([0,1,u[0],u[1]]).size<4)continue;++stats.dense_leaf_distinct;const leaves=new Set([0,1,u[0],u[1]]),outside=inside.filter(v=>!leaves.has(v)),boundary=Array(6).fill(0);for(const v of[0,1,2,...u])++boundary[v];const need=boundary.map(d=>4-d),G=graphs.get(need.join(""))||[];for(const E of G){++stats.degree_graphs;if(!fourConnected(E,u))continue;++stats.four_connected_graphs;const variable=E.findIndex(([a,b])=>a===outside[0]&&b===outside[1]);if(variable<0)continue;++stats.graphs_with_extra_edge;for(const labels of colourings(E,u,variable)){++stats.base_labelings;const z=constraints(E,u,labels,variable);stats.total_support_masks+=masks.length;stats.surviving_support_masks+=z.survivors;if(z.survivors){++stats.base_cases_with_survivor;if(examples.length<20)examples.push({u,outside,E,labels,z});}}}}
if(masks.length!==478)throw new Error("mask census mismatch");
const result={rank_at_least_two_support_masks:masks.length,stats,examples,elapsed_seconds:(Date.now()-started)/1000};
if(require.main===module)console.log(JSON.stringify(result,null,2));
module.exports=result;
