"use strict";

const fs=require("fs"),path=require("path");

function twoAnchorAudit(){
  const n=8,R=6,T=7,inside=[0,1,2,3,4,5],pairs=[];
  for(let a=0;a<6;++a)for(let b=a+1;b<6;++b)pairs.push([a,b]);
  function orderedDistinct(k){const out=[];function rec(a){if(a.length===k){out.push(a.slice());return;}for(const v of inside)if(!a.includes(v)){a.push(v);rec(a);a.pop();}}rec([]);return out;}
  const graphs=new Map();
  for(let mask=0;mask<1<<15;++mask){const d=Array(6).fill(0),E=[];for(let i=0;i<15;++i)if((mask>>>i)&1){const[a,b]=pairs[i];++d[a];++d[b];E.push([a,b]);}const k=d.join("");if(!graphs.has(k))graphs.set(k,[]);graphs.get(k).push(E);}
  function fourConnected(E,u){const A=Array.from({length:n},()=>[]);function add(a,b){A[a].push(b);A[b].push(a);}for(const e of E)add(...e);add(R,T);add(R,0);add(R,1);add(R,2);for(const v of u)add(T,v);
    for(let mask=0;mask<1<<n;++mask){let bits=0,start=-1,left=0;for(let v=0;v<n;++v){bits+=(mask>>>v)&1;if(!((mask>>>v)&1)){++left;if(start<0)start=v;}}if(bits>3)continue;const seen=new Set([start]),todo=[start];while(todo.length){const a=todo.pop();for(const b of A[a])if(!((mask>>>b)&1)&&!seen.has(b)){seen.add(b);todo.push(b);}}if(seen.size!==left)return false;}return true;}
  function graphPms(E){const A=Array.from({length:n},()=>[]),out=[];for(let i=0;i<E.length;++i){const[a,b]=E[i];A[a].push([b,i]);A[b].push([a,i]);}function rec(S,M){if(!S.size){out.push(M.slice());return;}const a=Math.min(...S);for(const[b,i]of A[a])if(S.has(b)){const U=new Set(S);U.delete(a);U.delete(b);M.push(i);rec(U,M);M.pop();}}rec(new Set(Array.from({length:n},(_,i)=>i)),[]);return out;}
  function permutations(a){if(!a.length)return[[]];const out=[];for(let i=0;i<a.length;++i)for(const t of permutations(a.slice(0,i).concat(a.slice(i+1))))out.push([a[i],...t]);return out;}
  function colourings(E,u){const leaves=[0,1,u[0],u[1]],inc=Array.from({length:6},()=>[]);for(let i=0;i<E.length;++i)for(const v of E[i])inc[v].push(i);const fixed=Array(E.length).fill(null),out=[];
    function recLeaf(pos){if(pos===leaves.length){const free=[];for(let i=0;i<E.length;++i)if(fixed[i]===null)free.push(i);function recFree(j){if(j===free.length){out.push(fixed.map(x=>x.slice()));return;}for(let a=0;a<3;++a)for(let b=0;b<3;++b){fixed[free[j]]=[a,b];recFree(j+1);}fixed[free[j]]=null;}recFree(0);return;}
      const v=leaves[pos],hasUnitBoundary=(v===2||v===u[2]),need=hasUnitBoundary?[0,1]:[0,1,2],edges=inc[v];if(edges.length!==need.length)throw new Error("leaf degree mismatch");
      for(const p of permutations(need)){let ok=true;const changed=[];for(let j=0;j<edges.length;++j){const i=edges[j],lab=[p[j],p[j]];if(fixed[i]&&fixed[i][0]!==p[j]){ok=false;break;}if(!fixed[i]){fixed[i]=lab;changed.push(i);}}if(ok)recLeaf(pos+1);for(const i of changed)fixed[i]=null;}}
    recLeaf(0);return out;}
  function support(i,labels){if(i===0)return[[0,0],[0,1],[1,0],[1,1]];if(i===1)return[[0,0],[1,0]];if(i===2)return[[0,1],[1,1]];if(i===3)return[[2,2]];if(i===4)return[[0,0],[1,0]];if(i===5)return[[0,1],[1,1]];if(i===6)return[[2,2]];return[labels[i-7]];}
  function screen(E,u,labels){const full=[[R,T],[R,0],[R,1],[R,2],[T,u[0]],[T,u[1]],[T,u[2]],...E],pm=graphPms(full),counts=new Map();for(const M of pm){const c=Array(n).fill(-1);function rec(j){if(j===M.length){const k=c.join("");counts.set(k,(counts.get(k)||0)+1);return;}const i=M[j],[a,b]=full[i];for(const[p,q]of support(i,labels)){c[a]=p;c[b]=q;rec(j+1);}c[a]=c[b]=-1;}rec(0);}let singletons=0;for(const[k,count]of counts)if(count===1&&new Set(k).size>1)++singletons;return singletons;}
  const stats={right_assignments:0,dense_leaf_distinct:0,degree_graphs:0,four_connected_graphs:0,unit_labelings:0,singleton_free:0,minimum_singletons:null};
  for(const u of orderedDistinct(3)){++stats.right_assignments;if(new Set([0,1,u[0],u[1]]).size<4)continue;++stats.dense_leaf_distinct;const boundary=Array(6).fill(0);for(const v of[0,1,2,...u])++boundary[v];const need=boundary.map(d=>4-d),G=graphs.get(need.join(""))||[];
    for(const E of G){++stats.degree_graphs;if(!fourConnected(E,u))continue;++stats.four_connected_graphs;for(const labels of colourings(E,u)){++stats.unit_labelings;const z=screen(E,u,labels);stats.minimum_singletons=stats.minimum_singletons===null?z:Math.min(stats.minimum_singletons,z);if(!z)++stats.singleton_free;}}}
  return stats;
}

function oneAnchorAudit(){
  const n=8,V=[0,1,2,3,4,5,6,7],R=[[0,1],[2,3],[4,5],[6,7]],profiles=[[0,1],[0,2],[0,1,2]];
  function edge(a,b){return a<b?[a,b]:[b,a];}function ek(a,b){return a<b?`${a},${b}`:`${b},${a}`;}function mk(M){return M.map(e=>e.join("")).join("|");}function tk(T){return T.map(mk).join(";");}
  function pms(v){if(!v.length)return[[]];const a=v[0],out=[];for(let i=1;i<v.length;++i)for(const m of pms(v.slice(1,i).concat(v.slice(i+1))))out.push([edge(a,v[i]),...m].sort((x,y)=>x[0]-y[0]||x[1]-y[1]));return out;}
  function dis(A,B){const s=new Set(A.map(e=>ek(...e)));return B.every(e=>!s.has(ek(...e)));}function con(E){const A=Array.from({length:n},()=>[]);for(const[a,b]of E){A[a].push(b);A[b].push(a);}const seen=new Set([0]),todo=[0];while(todo.length){const a=todo.pop();for(const b of A[a])if(!seen.has(b)){seen.add(b);todo.push(b);}}return seen.size===n;}
  function perms(a){if(!a.length)return[[]];const out=[];for(let i=0;i<a.length;++i)for(const t of perms(a.slice(0,i).concat(a.slice(i+1))))out.push([a[i],...t]);return out;}
  function maps(){const out=[];for(const p of perms([0,1,2,3]))for(let f=0;f<16;++f){const m=Array(n);for(let i=0;i<4;++i)for(let s=0;s<2;++s)m[2*i+s]=2*p[i]+(s^((f>>>i)&1));out.push(m);}return out;}
  function trans(T,m,p){const U=Array(3);for(let q=0;q<3;++q)U[p[q]]=T[q].map(([a,b])=>edge(m[a],m[b])).sort((x,y)=>x[0]-y[0]||x[1]-y[1]);return U;}
  function factorOrbits(){const all=pms(V),allow=all.filter(m=>dis(m,R)),S=new Map();for(const a of allow)for(const b of allow)if(dis(a,b))for(const c of allow)if(dis(a,c)&&dis(b,c)&&con([...R,...a,...b,...c])){const T=[a,b,c];S.set(tk(T),T);}const labelled=S.size,ms=maps(),ps=perms([0,1,2]),reps=[];while(S.size){const k=[...S.keys()].sort()[0],T=S.get(k);reps.push(T);for(const m of ms)for(const p of ps)S.delete(tk(trans(T,m,p)));}return{labelled,reps};}
  function matchingNumber2(mask){for(let a=0;a<3;++a)for(let b=a+1;b<3;++b)for(let c=0;c<3;++c)for(let d=c+1;d<3;++d)if((((mask>>>(3*a+c))&1)&&((mask>>>(3*b+d))&1))||(((mask>>>(3*a+d))&1)&&((mask>>>(3*b+c))&1)))return true;return false;}
  function profileMask(P){return P.reduce((s,q)=>s|(1<<q),0);}function qMasks(P,Q00){const rp=profileMask(P[0]),cp=profileMask(P[1]),out=[];for(let mask=0;mask<512;++mask){if(!!(mask&1)!==Q00||!matchingNumber2(mask))continue;let ok=true,rOutside=false,cOutside=false;for(let j=1;j<3;++j){let col=0;for(let i=0;i<3;++i)if((mask>>>(3*i+j))&1)col|=1<<i;if(col!==0&&col!==rp)ok=false;if(col===rp)rOutside=true;}for(let i=1;i<3;++i){let row=0;for(let j=0;j<3;++j)if((mask>>>(3*i+j))&1)row|=1<<j;if(row!==0&&row!==cp)ok=false;if(row===cp)cOutside=true;}if(ok&&rOutside&&cOutside)out.push(mask);}return out;}
  function graphPms(edges){const A=Array.from({length:n},()=>[]),out=[];for(let i=0;i<edges.length;++i){const[a,b]=edges[i];A[a].push([b,i]);A[b].push([a,i]);}function rec(S,M){if(!S.size){out.push(M.slice());return;}const a=Math.min(...S);for(const[b,i]of A[a])if(S.has(b)){const U=new Set(S);U.delete(a);U.delete(b);M.push(i);rec(U,M);M.pop();}}rec(new Set(V),[]);return out;}
  function singletonCount(edges,supports){const pm=graphPms(edges),counts=new Map();for(const M of pm){const c=Array(n).fill(-1);function rec(j){if(j===M.length){const k=c.join("");counts.set(k,(counts.get(k)||0)+1);return;}const i=M[j],[a,b]=edges[i];for(const[p,q]of supports[i]){c[a]=p;c[b]=q;rec(j+1);}c[a]=c[b]=-1;}rec(0);}let mixed=0;for(const[k,v]of counts)if(v===1&&new Set(k).size>1)++mixed;return mixed;}
  function unitSupport(a,b){return[[a,b]];}function denseAnchorSupport(root,leaf,P,a,b){return a===root?P.map(q=>[q,0]):P.map(q=>[0,q]);}function matrixSupport(root0,root1,mask,a,b){const out=[];for(let i=0;i<3;++i)for(let j=0;j<3;++j)if((mask>>>(3*i+j))&1)out.push(a===root0?[i,j]:[j,i]);return out;}function partner(M,v){const e=M.find(x=>x.includes(v));return e[0]===v?e[1]:e[0];}
  function auditM0(T,qIndex,Pr,Pt,Qmask,d){const qEdge=T[0][qIndex],[r,t]=qEdge,ar=partner(R,r),at=partner(R,t),edges=[...T[0],...T[1],...T[2],...R],supports=[];for(let q=0;q<3;++q)for(const e of T[q])supports.push(unitSupport(q,q));for(const e of R){if(e.includes(r))supports.push(denseAnchorSupport(r,ar,Pr,...e));else if(e.includes(t))supports.push(denseAnchorSupport(t,at,Pt,...e));else supports.push(unitSupport(d[e[0]],d[e[1]]));}supports[qIndex]=matrixSupport(r,t,Qmask,...T[0][qIndex]);return singletonCount(edges,supports);}
  function auditR(T,rIndex,Pr,Pt,Qmask,d){const qEdge=R[rIndex],[r,t]=qEdge,ar=partner(T[0],r),at=partner(T[0],t),edges=[...T[0],...T[1],...T[2],...R],supports=[];for(let q=0;q<3;++q)for(const e of T[q]){if(q===0&&e.includes(r))supports.push(denseAnchorSupport(r,ar,Pr,...e));else if(q===0&&e.includes(t))supports.push(denseAnchorSupport(t,at,Pt,...e));else supports.push(unitSupport(q,q));}for(let i=0;i<4;++i){const e=R[i];supports.push(i===rIndex?matrixSupport(r,t,Qmask,...e):unitSupport(d[e[0]],d[e[1]]));}return singletonCount(edges,supports);}
  function orientedPairs(root0,pairs,a){return a===root0?pairs:pairs.map(([x,y])=>[y,x]);}
  function auditRetraction(T,qIndex,r,t,P,b,d){const ar=partner(R,r),at=partner(R,t),edges=[...T[0],...T[1],...T[2],...R],supports=[];for(let q=0;q<3;++q)for(const e of T[q])supports.push(unitSupport(q,q));for(const e of R){if(e.includes(r))supports.push(denseAnchorSupport(r,ar,P,...e));else if(e.includes(t))supports.push(orientedPairs(t,[[b,0]],e[0]));else supports.push(unitSupport(d[e[0]],d[e[1]]));}supports[qIndex]=orientedPairs(r,[[0,0],...P.map(x=>[x,b])],T[0][qIndex][0]);return singletonCount(edges,supports);}
  const{labelled,reps}=factorOrbits(),stats={M0:{configurations:0,singleton_free:0,minimum:null,profile_masks:{}},R:{configurations:0,singleton_free:0,minimum:null,profile_masks:{}},retraction:{configurations:0,singleton_free:0,minimum:null}};
  for(const Pr of profiles)for(const Pt of profiles){const key=`${Pr.join("")}|${Pt.join("")}`,m1=qMasks([Pr,Pt],true),m0=qMasks([Pr,Pt],false);stats.M0.profile_masks[key]=m1.length;stats.R.profile_masks[key]=m0.length;
    for(const T of reps)for(let i=0;i<4;++i){const[r,t]=T[0][i],usedR=new Set([R.findIndex(e=>e.includes(r)),R.findIndex(e=>e.includes(t))]),free=V.filter(v=>!R.some((e,j)=>usedR.has(j)&&e.includes(v)));for(let a=0;a<3**free.length;++a){let x=a,d=Array(n).fill(-1);for(const v of free){d[v]=x%3;x=Math.floor(x/3);}for(const Q of m1){const w=auditM0(T,i,Pr,Pt,Q,d);++stats.M0.configurations;stats.M0.minimum=stats.M0.minimum===null?w:Math.min(stats.M0.minimum,w);if(!w)++stats.M0.singleton_free;}}
      const[r0,t0]=R[i],freeR=V.filter(v=>v!==r0&&v!==t0);for(let a=0;a<3**freeR.length;++a){let x=a,d=Array(n).fill(-1);for(const v of freeR){d[v]=x%3;x=Math.floor(x/3);}for(const Q of m0){const w=auditR(T,i,Pr,Pt,Q,d);++stats.R.configurations;stats.R.minimum=stats.R.minimum===null?w:Math.min(stats.R.minimum,w);if(!w)++stats.R.singleton_free;}}}}
  for(const P of profiles)for(const b of[1,2])for(const T of reps)for(let i=0;i<4;++i){const[a,c]=T[0][i];for(const[r,t]of[[a,c],[c,a]]){const usedR=new Set([R.findIndex(e=>e.includes(r)),R.findIndex(e=>e.includes(t))]),free=V.filter(v=>!R.some((e,j)=>usedR.has(j)&&e.includes(v)));for(let z=0;z<3**free.length;++z){let x=z,d=Array(n).fill(-1);for(const v of free){d[v]=x%3;x=Math.floor(x/3);}const w=auditRetraction(T,i,r,t,P,b,d);++stats.retraction.configurations;stats.retraction.minimum=stats.retraction.minimum===null?w:Math.min(stats.retraction.minimum,w);if(!w)++stats.retraction.singleton_free;}}}
  return{connected_labelled_factor_triples:labelled,factor_triple_orbits:reps.length,...stats};
}

const started=Date.now(),two=twoAnchorAudit(),one=oneAnchorAudit();
const summary={schema_version:1,series:"run-027",mode:"exact_rank_two_boundary_stars",n:8,two_anchor:two,one_anchor:{connected_labelled_factor_triples:one.connected_labelled_factor_triples,factor_triple_orbits:one.factor_triple_orbits,symmetric_M0:one.M0,symmetric_R:one.R,retraction:one.retraction},elapsed_seconds:(Date.now()-started)/1000};
if(two.right_assignments!==120||two.dense_leaf_distinct!==48||two.degree_graphs!==1704||two.four_connected_graphs!==1440||two.unit_labelings!==170280||two.singleton_free!==0||two.minimum_singletons!==14||one.connected_labelled_factor_triples!==27456||one.factor_triple_orbits!==39||one.M0.configurations!==113724||one.M0.singleton_free!==0||one.M0.minimum!==10||one.R.configurations!==1023516||one.R.singleton_free!==0||one.R.minimum!==10||one.retraction.configurations!==151632||one.retraction.singleton_free!==0||one.retraction.minimum!==9)throw new Error("rank-two boundary-star census mismatch");
const out=path.join(__dirname,"local-runs","run-027-summary.json");fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(summary,null,2)+"\n");process.stdout.write(JSON.stringify(summary,null,2)+"\n");
