"use strict";

const fs=require("fs"),path=require("path"),n=8,V=[0,1,2,3,4,5,6,7],R=[[0,1],[2,3],[4,5],[6,7]];
function edge(a,b){return a<b?[a,b]:[b,a];}function ek(a,b){return a<b?`${a},${b}`:`${b},${a}`;}function mk(M){return M.map(e=>e.join("")).join("|");}function tk(T){return T.map(mk).join(";");}
function pms(v){if(!v.length)return[[]];const a=v[0],o=[];for(let i=1;i<v.length;++i)for(const m of pms(v.slice(1,i).concat(v.slice(i+1))))o.push([edge(a,v[i]),...m].sort((x,y)=>x[0]-y[0]||x[1]-y[1]));return o;}
function dis(A,B){const s=new Set(A.map(e=>ek(...e)));return B.every(e=>!s.has(ek(...e)));}function con(E){const A=Array.from({length:n},()=>[]);for(const[a,b]of E){A[a].push(b);A[b].push(a);}const s=new Set([0]),z=[0];while(z.length){const a=z.pop();for(const b of A[a])if(!s.has(b)){s.add(b);z.push(b);}}return s.size===n;}
function perms(a){if(!a.length)return[[]];const o=[];for(let i=0;i<a.length;++i)for(const t of perms(a.slice(0,i).concat(a.slice(i+1))))o.push([a[i],...t]);return o;}
function maps(){const o=[];for(const p of perms([0,1,2,3]))for(let f=0;f<16;++f){const m=Array(n);for(let i=0;i<4;++i)for(let s=0;s<2;++s)m[2*i+s]=2*p[i]+(s^((f>>>i)&1));o.push(m);}return o;}
function trans(T,m,p){const U=Array(3);for(let q=0;q<3;++q)U[p[q]]=T[q].map(([a,b])=>edge(m[a],m[b])).sort((x,y)=>x[0]-y[0]||x[1]-y[1]);return U;}
function factorOrbits(){const all=pms(V),allow=all.filter(m=>dis(m,R)),S=new Map();for(const a of allow)for(const b of allow)if(dis(a,b))for(const c of allow)if(dis(a,c)&&dis(b,c)&&con([...R,...a,...b,...c])){const T=[a,b,c];S.set(tk(T),T);}const labelled=S.size,ms=maps(),ps=perms([0,1,2]),reps=[];while(S.size){const k=[...S.keys()].sort()[0],T=S.get(k);reps.push(T);for(const m of ms)for(const p of ps)S.delete(tk(trans(T,m,p)));}return{labelled,reps};}
function graphPms(vertices,L){const o=[];function rec(S,M){if(!S.size){o.push(M.slice());return;}const a=Math.min(...S);for(const[k,{e:[x,y]}]of L){if(x!==a&&y!==a)continue;const b=x===a?y:x;if(!S.has(b))continue;const T=new Set(S);T.delete(a);T.delete(b);M.push(k);rec(T,M);M.pop();}}rec(new Set(vertices),[]);return o;}
function induced(M,L){const c=Array(n).fill(-1);for(const k of M){const{e:[a,b],c:[x,y]}=L.get(k);if((c[a]>=0&&c[a]!==x)||(c[b]>=0&&c[b]!==y))return null;c[a]=x;c[b]=y;}return c;}function comp(M,L,c){return M.every(k=>{const{e:[a,b],c:[x,y]}=L.get(k);return c[a]===x&&c[b]===y;});}
function robust(T,mask,d){const L=new Map();for(let q=0;q<3;++q)for(const[a,b]of T[q])L.set(ek(a,b),{e:[a,b],c:[q,q]});for(let i=0;i<4;++i)if(!((mask>>>i)&1)){const[a,b]=R[i];L.set(ek(a,b),{e:[a,b],c:[d[a],d[b]]});}
 const by=new Map();for(const M of graphPms(V,L)){const c=induced(M,L);if(!c)continue;const k=c.join(""),z=by.get(k)||{c,count:0};++z.count;by.set(k,z);}const C=[];for(let sub=mask;sub;sub=(sub-1)&mask){const del=new Set();for(let i=0;i<4;++i)if((sub>>>i)&1)for(const v of R[i])del.add(v);C.push(graphPms(V.filter(v=>!del.has(v)),L));}
 let w=0;for(const{c,count}of by.values())if(count===1&&!c.every(q=>q===c[0])&&C.every(P=>!P.some(M=>comp(M,L,c))))++w;return w;}
function census(reps){const out={},failures=[];for(let size=1;size<=3;++size){let configurations=0,min=null,fail=0;const hist=new Map();for(let oi=0;oi<reps.length;++oi)for(let mask=1;mask<15;++mask){let bits=0;for(let i=0;i<4;++i)bits+=(mask>>>i)&1;if(bits!==size)continue;const free=V.filter(v=>!R.some((e,i)=>((mask>>>i)&1)&&e.includes(v)));
   for(let a=0;a<3**free.length;++a){let x=a;const d=Array(n).fill(-1);for(const v of free){d[v]=x%3;x=Math.floor(x/3);}const w=robust(reps[oi],mask,d);++configurations;min=min===null?w:Math.min(min,w);hist.set(w,(hist.get(w)||0)+1);if(!w){++fail;failures.push({size,orbit:oi,mask,d});}}}
  out[size]={configurations,minimum_witnesses:min,witness_count_histogram:Object.fromEntries([...hist].sort((a,b)=>a[0]-b[0])),failures:fail};}return{out,failures};}
const colourPerms=perms([0,1,2]);function highRank(mask){for(let a=0;a<3;++a)for(let b=a+1;b<3;++b)for(let c=0;c<3;++c)for(let d=c+1;d<3;++d)if((((mask>>>(3*a+c))&1)&&((mask>>>(3*b+d))&1))||(((mask>>>(3*a+d))&1)&&((mask>>>(3*b+c))&1)))return true;return false;}
const masks=Array.from({length:512},(_,i)=>i).filter(highRank);function decode(k){const c=[];for(let i=0;i<n;++i){c.push(k%3);k=Math.floor(k/3);}return c;}
function termConstraints(T,mask,d){const dense=[];for(let i=0;i<4;++i)if((mask>>>i)&1)dense.push(i);const edges=[],labels=[],pos=new Map();for(let q=0;q<3;++q)for(const e of T[q]){edges.push(e);labels.push([q,q]);}for(let i=0;i<4;++i){edges.push(R[i]);if((mask>>>i)&1){pos.set(edges.length-1,dense.indexOf(i));labels.push(null);}else labels.push([d[R[i][0]],d[R[i][1]]]);}
 const local=new Map(edges.map((e,i)=>[String(i),{e,c:labels[i]}])),pm=graphPms(V,local),constraints=[];for(let ck=0;ck<3**n;++ck){const c=decode(ck);if(c.every(q=>q===c[0]))continue;const terms=[];for(const M0 of pm){let ok=true,req=Array(dense.length).fill(0);for(const s of M0){const i=+s,[a,b]=edges[i],lab=labels[i];if(lab){if(c[a]!==lab[0]||c[b]!==lab[1]){ok=false;break;}}else req[pos.get(i)]=1;}if(ok)terms.push(req);}if(terms.length){const bits=dense.map(i=>{const[a,b]=R[i];return 1<<(3*c[a]+c[b]);});constraints.push({bits,terms});}}
 return{dense,underlying_perfect_matchings:pm.length,constraints};}
function screenTwo(T,record){const data=termConstraints(T,record.mask,record.d);let surviving=0;for(const A of masks)for(const B of masks){let ok=true;for(const z of data.constraints){let count=0;for(const req of z.terms)if((!req[0]||(A&z.bits[0]))&&(!req[1]||(B&z.bits[1])))++count;if(count===1){ok=false;break;}}if(ok)++surviving;}return{surviving,underlying_perfect_matchings:data.underlying_perfect_matchings,mixed_constraints:data.constraints.length};}
function screenThree(T,record){const data=termConstraints(T,record.mask,record.d);let survivingPairs=0;for(const A of masks)for(const B of masks){let include=0,exclude=0,invalid=false;for(const z of data.constraints){let c0=0,c1=0;for(const req of z.terms)if((!req[0]||(A&z.bits[0]))&&(!req[1]||(B&z.bits[1]))){if(req[2])++c1;else{++c0;++c1;}}if(c0===1&&c1===1){invalid=true;break;}if(c0===1)include|=z.bits[2];if(c1===1)exclude|=z.bits[2];if(include&exclude){invalid=true;break;}}if(!invalid&&masks.some(C=>(C&include)===include&&!(C&exclude)))++survivingPairs;}return{survivingPairs,underlying_perfect_matchings:data.underlying_perfect_matchings,mixed_constraints:data.constraints.length};}

const started=Date.now(),{labelled,reps}=factorOrbits(),C=census(reps),two=C.failures.filter(x=>x.size===2),three=C.failures.filter(x=>x.size===3);let twoSurvivors=0,threeSurvivingPairs=0;for(const r of two)twoSurvivors+=screenTwo(reps[r.orbit],r).surviving;for(const r of three)threeSurvivingPairs+=screenThree(reps[r.orbit],r).survivingPairs;
const summary={schema_version:1,series:"run-026",mode:"exact_diagonal_matching",n,connected_labelled_factor_triples:labelled,factor_triple_orbits:reps.length,robust_census:C.out,
 support_masks_with_matching_number_at_least_two:masks.length,two_edge_screen:{residues:two.length,mask_pairs_per_residue:masks.length**2,total_mask_pairs:two.length*masks.length**2,survivors:twoSurvivors},
 three_edge_screen:{residues:three.length,first_two_mask_pairs_per_residue:masks.length**2,total_first_two_mask_pairs:three.length*masks.length**2,surviving_pairs:threeSurvivingPairs},elapsed_seconds:(Date.now()-started)/1000};
const expected={one:[113724,0],two:[18954,4],three:[1404,84]};if(labelled!==27456||reps.length!==39||masks.length!==478||C.out[1].configurations!==expected.one[0]||C.out[1].failures!==0||C.out[2].configurations!==expected.two[0]||C.out[2].failures!==4||C.out[3].configurations!==expected.three[0]||C.out[3].failures!==84||twoSurvivors||threeSurvivingPairs)throw new Error("diagonal matching census mismatch");
const out=path.join(__dirname,"local-runs","run-026-summary.json");fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(summary,null,2)+"\n");process.stdout.write(JSON.stringify(summary,null,2)+"\n");
