#include <boost/multiprecision/cpp_int.hpp>
#include <boost/multiprecision/integer.hpp>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <numeric>
#include <random>
#include <sstream>
#include <string>
#include <vector>
using boost::multiprecision::cpp_int;
cpp_int ax(cpp_int a){return a<0?-a:a;}
cpp_int gx(cpp_int a,cpp_int b){a=ax(a);b=ax(b);while(b!=0){cpp_int r=a%b;a=b;b=r;}return a;}
struct R{cpp_int n,d;R(cpp_int a=0,cpp_int b=1):n(a),d(b){norm();}void norm(){if(d==0)throw std::runtime_error("zero den");if(d<0){d=-d;n=-n;}cpp_int g=gx(n,d);if(g!=0){n/=g;d/=g;}}};
R mul(R a,R b){cpp_int g1=gx(a.n,b.d),g2=gx(b.n,a.d);a.n/=g1;b.d/=g1;b.n/=g2;a.d/=g2;return R(a.n*b.n,a.d*b.d);}
R divr(R a,R b){return mul(a,R(b.d,b.n));}
R addr(R a,R b){cpp_int g=gx(a.d,b.d);return R(a.n*(b.d/g)+b.n*(a.d/g),a.d*(b.d/g));}
R cub(R a){return mul(mul(a,a),a);}
bool eq(R const&a,R const&b){return a.n==b.n&&a.d==b.d;}
bool lt(R const&a,R const&b){return a.n*b.d<b.n*a.d;}
std::string ss(cpp_int const&x){return x.convert_to<std::string>();}
struct E{R r[2],f[2];std::array<R,2> alt[2];};
E ev(cpp_int a,cpp_int b){cpp_int a2=a*a,b2=b*b,ab=a*b;cpp_int p=b2-ab+3*a2,q=b2+ab+3*a2;cpp_int a3=a2*a,b3=b2*b,ab2=a*b2;cpp_int c=b3-2*ab2-3*a3,d=b3+2*ab2+3*a3;E e;e.r[0]=R(p,q);e.r[1]=R(c,d);e.f[0]=R(d*d*d-c*c*c,q*q*q*b3);e.f[1]=R(b3*(q*q*q-p*p*p),d*d*d);e.alt[0]={R(c,q*b),R(d,q*b)};e.alt[1]={R(p*b,d),R(q*b,d)};return e;}
std::pair<uint64_t,uint64_t> smp(std::mt19937_64&g,uint64_t lo,uint64_t hi){for(;;){uint64_t b=lo+g()%(hi-lo+1);if(b<3)continue;uint64_t m=(b-1)/2;if(!m)continue;uint64_t a=1+g()%m;if(std::gcd(a,b)==1)return{a,b};}}
bool cancel3(std::array<R,3>d,int&big){std::array<int,3>idx{0,1,2};std::sort(idx.begin(),idx.end(),[&](int i,int j){return lt(d[i],d[j]);});R sum=addr(d[idx[0]],d[idx[1]]);if(eq(sum,d[idx[2]])){big=idx[2];return true;}return false;}
bool verify_build(const std::array<int,3>&t,const std::array<E,3>&e,int big,std::array<R,9>&z,std::array<cpp_int,9>&ints,cpp_int&S){R one(1),a=e[2].r[t[2]],b=e[1].r[t[1]];z[0]=a;z[1]=b;z[2]=one;auto bc=e[1].alt[t[1]],ac=e[2].alt[t[2]],ab=e[0].alt[t[0]];ab[0]=mul(ab[0],b);ab[1]=mul(ab[1],b);std::array<std::array<R,2>,3>pairs{bc,ac,ab};for(int k=0;k<3;++k){bool pos=(k==big);R lo=pairs[k][0],hi=pairs[k][1],first=pos?hi:lo,second=pos?lo:hi;if(k==0){z[3]=first;z[6]=second;}else if(k==1){z[4]=first;z[7]=second;}else{z[5]=first;z[8]=second;}}for(auto&x:z)if(x.n<=0)return false;for(int i=0;i<9;++i)for(int j=i+1;j<9;++j)if(eq(z[i],z[j]))return false;cpp_int L=1;for(auto&x:z){cpp_int g=gx(L,x.d);L=(L/g)*x.d;}cpp_int G=0;for(int i=0;i<9;++i){ints[i]=z[i].n*(L/z[i].d);G=gx(G,ints[i]);}if(G!=0)for(auto&x:ints)x/=G;auto c3=[](cpp_int x){return x*x*x;};std::array<cpp_int,6>sums{c3(ints[0])+c3(ints[1])+c3(ints[2]),c3(ints[3])+c3(ints[4])+c3(ints[5]),c3(ints[6])+c3(ints[7])+c3(ints[8]),c3(ints[0])+c3(ints[3])+c3(ints[6]),c3(ints[1])+c3(ints[4])+c3(ints[7]),c3(ints[2])+c3(ints[5])+c3(ints[8])};for(int i=1;i<6;++i)if(sums[i]!=sums[0])return false;S=sums[0];return true;}
int main(int argc,char**argv){int wid=0,wcount=1,seconds=30;uint64_t seed=20260817ULL;std::string out="-";for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="--worker"&&i+1<argc)wid=std::stoi(argv[++i]);else if(a=="--workers"&&i+1<argc)wcount=std::stoi(argv[++i]);else if(a=="--seconds"&&i+1<argc)seconds=std::stoi(argv[++i]);else if(a=="--seed"&&i+1<argc)seed=std::stoull(argv[++i]);else if(a=="--out"&&i+1<argc)out=argv[++i];}std::mt19937_64 gen(seed^(0x9e3779b97f4a7c15ULL*(wid+1)));std::array<std::array<int,3>,6>T{{{{0,0,1}},{{0,1,0}},{{0,1,1}},{{1,0,0}},{{1,0,1}},{{1,1,0}}}};std::array<std::pair<uint64_t,uint64_t>,5>bands{{{3,100},{101,1000},{1001,10000},{10001,100000},{100001,1000000}}};uint64_t attempts=0,compatible=0,cancellations=0;std::array<uint64_t,6>attb{},compb{};std::vector<std::string>found;auto st=std::chrono::steady_clock::now();while(true){if((attempts&1023ULL)==0){auto now=std::chrono::steady_clock::now();if(std::chrono::duration_cast<std::chrono::seconds>(now-st).count()>=seconds)break;}int bi=(int)(attempts%6);auto tt=T[bi];int dep=tt[0]==0?0:(tt[1]==0?1:2);int band=(wid+(int)(attempts/6))%5;auto[lo,hi]=bands[band];std::array<E,3>ee;for(int j=0;j<3;++j)if(j!=dep){auto p=smp(gen,lo,hi);ee[j]=ev(p.first,p.second);}R target;if(dep==0)target=divr(ee[2].r[tt[2]],ee[1].r[tt[1]]);else if(dep==1)target=divr(ee[2].r[tt[2]],ee[0].r[tt[0]]);else target=mul(ee[0].r[tt[0]],ee[1].r[tt[1]]);++attempts;++attb[bi];if(!(target.n>0&&target.n<target.d&&9*target.n>5*target.d))continue;cpp_int dn=target.d-target.n,spv=target.d+target.n,disc=spv*spv-12*dn*dn;if(disc<0)continue;cpp_int rt=sqrt(disc);if(rt*rt!=disc)continue;for(int sg:{-1,1}){cpp_int xn=spv+(sg<0?-rt:rt),xd=6*dn;if(xn<=0||2*xn>=xd)continue;R xr(xn,xd);ee[dep]=ev(xr.n,xr.d);R check;if(dep==0)check=divr(ee[2].r[tt[2]],ee[1].r[tt[1]]);else if(dep==1)check=divr(ee[2].r[tt[2]],ee[0].r[tt[0]]);else check=mul(ee[0].r[tt[0]],ee[1].r[tt[1]]);if(!eq(ee[dep].r[0],check))continue;++compatible;++compb[bi];R da=mul(cub(ee[1].r[tt[1]]),ee[0].f[tt[0]]),db=ee[1].f[tt[1]],dc=ee[2].f[tt[2]];int big=-1;if(!cancel3({da,db,dc},big))continue;++cancellations;std::array<R,9>z;std::array<cpp_int,9>ints;cpp_int S;if(verify_build(tt,ee,big,z,ints,S)){std::ostringstream q;q<<"{\"case\":"<<bi<<",\"bases\":[";for(int k=0;k<9;++k){if(k)q<<",";q<<ss(ints[k]);}q<<"],\"S\":\""<<ss(S)<<"\"}";found.push_back(q.str());}break;}}auto elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-st).count();std::ostream*op=&std::cout;std::ofstream fo;if(out!="-"){fo.open(out);op=&fo;}auto&o=*op;o<<"{\n\"worker\":"<<wid<<",\"workers\":"<<wcount<<",\"attempts\":"<<attempts<<",\"compatible\":"<<compatible<<",\"cancellations\":"<<cancellations<<",\"elapsed\":"<<elapsed<<",\"attempts_by_case\":[";for(int i=0;i<6;++i){if(i)o<<",";o<<attb[i];}o<<"],\"compatible_by_case\":[";for(int i=0;i<6;++i){if(i)o<<",";o<<compb[i];}o<<"],\"found\":[";for(size_t i=0;i<found.size();++i){if(i)o<<",";o<<found[i];}o<<"]\n}\n";}
