#!/usr/bin/env python3
"""Exact algebra certificate for the root-grid reduction.

No floating point arithmetic is used.  The file verifies:
1. the four adjacent cube-rectangle equations for a 3x3 additive cube grid;
2. the generic quadratic equation in the absolute lower root x;
3. its discriminant factorization;
4. the four-rectangle reconstruction of the whole 3x3 root grid.
"""
import sympy as sp

x,a,b,h,j,d,e,f,g = sp.symbols('x a b h j d e f g')


def Q(X,A,H,D):
    S = X + A + H
    return sp.expand(D*(3*S**2 - 3*D*S + D**2) - 3*A*H*(2*X + A + H))


def rect(X,A,H,D):
    return sp.expand(X**3 + (X+A+H-D)**3 - (X+H)**3 - (X+A)**3)

# One 2x2 rectangle is equivalent to Q=0.
assert sp.expand(rect(x,a,h,d) + Q(x,a,h,d)) == 0

# Q is quadratic in the absolute lower root x.
P = sp.Poly(Q(x,a,h,d), x)
assert P.degree() == 2
assert P.LC() == 3*d

# Exact discriminant factorization.
Delta = sp.factor(sp.discriminant(P))
Delta_expected = sp.factor(3*(12*a*h*(a-d)*(h-d) - d**4))
assert sp.expand(Delta - Delta_expected) == 0

# If the four roots are integers and their cube sums agree, then d is a
# multiple of 3 immediately from n^3 == n (mod 3):
#   x^3+w^3=y^3+z^3 => x+w == y+z (mod 3),
# and d=y+z-x-w.
# The symbolic identity below records d=y+z-x-w for the chosen coordinates.
y=x+h
z=x+a
w=x+a+h-d
assert sp.expand(y+z-x-w-d) == 0

# Parameterize all nine roots by the two first-row gaps h,j, the two first-
# column gaps a,b, and the four positive mixed deficits d,e,f,g.
r00=x
r01=x+h
r02=x+h+j
r10=x+a
r11=x+a+h-d
r12=x+a+h+j-d-e
r20=x+a+b
r21=x+a+b+h-d-f
r22=x+a+b+h+j-d-e-f-g
R=[[r00,r01,r02],[r10,r11,r12],[r20,r21,r22]]

# The four adjacent rectangle equations are exactly the four Q equations.
Q00=Q(x,a,h,d)
Q01=Q(x+h,a-d,j,e)
Q10=Q(x+a,b,h-d,f)
Q11=Q(x+a+h-d,b-f,j-e,g)
rects=[
    sp.expand(R[0][0]**3+R[1][1]**3-R[0][1]**3-R[1][0]**3),
    sp.expand(R[0][1]**3+R[1][2]**3-R[0][2]**3-R[1][1]**3),
    sp.expand(R[1][0]**3+R[2][1]**3-R[1][1]**3-R[2][0]**3),
    sp.expand(R[1][1]**3+R[2][2]**3-R[1][2]**3-R[2][1]**3),
]
for lhs,q in zip(rects,[Q00,Q01,Q10,Q11]):
    assert sp.expand(lhs + q) == 0

# Four vanishing adjacent mixed differences imply the cube values have
# Cartesian additive form C_i+T_j.  Verify an explicit reconstruction:
C=[R[i][0]**3 for i in range(3)]
T=[sp.expand(R[0][j]**3-R[0][0]**3) for j in range(3)]
# Reduce each residual modulo the ideal generated by the four rectangle
# equations via a Groebner basis.  Every residual must vanish.
G=sp.groebner([Q00,Q01,Q10,Q11],x,a,b,h,j,d,e,f,g,order='grevlex')
for i in range(3):
    for jj in range(3):
        residual=sp.expand(R[i][jj]**3-C[i]-T[jj])
        assert G.reduce(residual)[1] == 0

print('r27 exact root-grid certificate: PASS')
print('generic discriminant =', Delta_expected)
print('necessary congruence: each adjacent deficit d,e,f,g is 0 mod 3')
print('four Q equations are equivalent to a 3x3 Cartesian additive cube grid')
