#include <bits/stdc++.h>
#include <boost/multiprecision/cpp_int.hpp>
#include <omp.h>
using namespace std;using boost::multiprecision::uint128_t;using boost::multiprecision::uint512_t;using u64=uint64_t;using u128n=__uint128_t;
struct FE{int rank,b;uint8_t e;};struct BI{u64 q;int maxe;vector<u64>pw;};struct CTX{int n,B;vector<uint128_t>P;vector<vector<FE>>F;vector<BI>bs;vector<vector<vector<u64>>>inv;};struct T3C{int rank,b,e,src;u64 r;};
static uint128_t parse128(const string&s){uint128_t x=0;for(char c:s)x=x*10+(c-'0');return x;}static u64 invmod(u64 a,u64 m){__int128 t=0,nt=1,r=m,nr=a%m;while(nr){u64 q=r/nr;__int128 z=t-(__int128)q*nt;t=nt;nt=z;z=r-(__int128)q*nr;r=nr;nr=z;}if(r!=1)return 0;t%=m;if(t<0)t+=m;return(u64)t;}static vector<pair<u64,int>>fac(uint128_t n){vector<pair<u64,int>>f;for(u64 q=2;q<=100000&&uint128_t(q)*q<=n;q+=(q==2?1:2)){if(n%q)continue;int e=0;do{n/=q;e++;}while(n%q==0);f.push_back({q,e});}if(n>1)f.push_back({n.convert_to<u64>(),1});return f;}
static bool crtstep(uint512_t&x,uint512_t&M,const uint512_t&B,u64 m,u64 r){if(!r&&m!=1)return false;if(M>B){return (x%m).convert_to<u64>()==r;}u64 xm=(x%m).convert_to<u64>(),Mm=(M%m).convert_to<u64>(),iv=invmod(Mm,m);if(!iv)return false;u64 k=(u128n)((r+m-xm)%m)*iv%m;x+=M*k;M*=m;return !(M>B&&x>B);}
static int buildT3(const CTX&C,int j,int t,int u,T3C*out){size_t a=0,b=0,c=0;int n=0;while(a<C.F[j].size()||b<C.F[t].size()||c<C.F[u].size()){int rank=INT_MAX;if(a<C.F[j].size())rank=min(rank,C.F[j][a].rank);if(b<C.F[t].size())rank=min(rank,C.F[t][b].rank);if(c<C.F[u].size())rank=min(rank,C.F[u][c].rank);int ej=0,et=0,eu=0,base=-1;if(a<C.F[j].size()&&C.F[j][a].rank==rank){ej=C.F[j][a].e;base=C.F[j][a].b;a++;}if(b<C.F[t].size()&&C.F[t][b].rank==rank){et=C.F[t][b].e;base=C.F[t][b].b;b++;}if(c<C.F[u].size()&&C.F[u][c].rank==rank){eu=C.F[u][c].e;base=C.F[u][c].b;c++;}int e=max({ej,et,eu}),s=(ej==e?0:(et==e?1:2));u64 m=C.bs[base].pw[e],r=s==0?(u128n)C.inv[base][e][t]*C.inv[base][e][u]%m:s==1?(u128n)C.inv[base][e][j]*C.inv[base][e][u]%m:(u128n)C.inv[base][e][j]*C.inv[base][e][t]%m;out[n++]={rank,base,e,s,r};}return n;}
static bool crtT3(const CTX&C,int j,int t,int u,const uint512_t&B,T3C*out,int&nc,uint512_t&x,uint512_t&M){nc=buildT3(C,j,t,u,out);x=0;M=1;for(int z=0;z<nc;z++){u64 m=C.bs[out[z].b].pw[out[z].e];if(!crtstep(x,M,B,m,out[z].r))return false;}return x<=B;}
static bool crt4from3(const CTX&C,int j,int t,int u,int v,const T3C*st,int ns,const uint512_t&B,uint512_t&x,uint512_t&M){size_t a=0,b=0;x=0;M=1;while(a<(size_t)ns||b<C.F[v].size()){int r1=a<(size_t)ns?st[a].rank:INT_MAX,r2=b<C.F[v].size()?C.F[v][b].rank:INT_MAX;int base,e;u64 res,m;if(r1<r2){base=st[a].b;e=st[a].e;m=C.bs[base].pw[e];res=(u128n)st[a].r*C.inv[base][e][v]%m;a++;}else if(r2<r1){base=C.F[v][b].b;e=C.F[v][b].e;m=C.bs[base].pw[e];res=(u128n)C.inv[base][e][j]*C.inv[base][e][t]%m*C.inv[base][e][u]%m;b++;}else{base=st[a].b;int e3=st[a].e,ev=C.F[v][b].e;if(ev>e3){e=ev;m=C.bs[base].pw[e];res=(u128n)C.inv[base][e][j]*C.inv[base][e][t]%m*C.inv[base][e][u]%m;}else{e=e3;m=C.bs[base].pw[e];res=(u128n)st[a].r*C.inv[base][e][v]%m;}a++;b++;}if(!crtstep(x,M,B,m,res))return false;}return x<=B;}
static bool crtH(const CTX&C,const int*top,int H,const uint512_t&B,uint512_t&x,uint512_t&M){size_t p[8]={};x=0;M=1;while(1){int rank=INT_MAX;bool any=0;for(int h=0;h<H;h++)if(p[h]<C.F[top[h]].size()){any=1;rank=min(rank,C.F[top[h]][p[h]].rank);}if(!any)break;int base=-1,e=0,src=-1;for(int h=0;h<H;h++)if(p[h]<C.F[top[h]].size()&&C.F[top[h]][p[h]].rank==rank){auto z=C.F[top[h]][p[h]++];base=z.b;if(z.e>e){e=z.e;src=h;}}u64 m=C.bs[base].pw[e],r=1;for(int h=0;h<H;h++)if(h!=src)r=(u128n)r*C.inv[base][e][top[h]]%m;if(!crtstep(x,M,B,m,r))return false;}return x<=B;}
static uint512_t prodBelow(const CTX&C,int idx,int k){uint512_t z=1;for(int a=1;a<=k;a++)z*=C.P[idx-a];return z;}
int main(int ac,char**av){if(ac<2)return 1;ifstream in(av[1]);CTX C;string s;while(in>>s)C.P.push_back(parse128(s));C.n=ac>2?min<int>(stoi(av[2]),C.P.size()):C.P.size();C.P.resize(C.n);int th=ac>3?stoi(av[3]):4,U0=ac>4?stoi(av[4]):6,U1=ac>5?min(stoi(av[5]),C.n-3):C.n-3;cerr<<"loaded n="<<C.n<<" u="<<U0<<".."<<U1<<"\n";vector<map<u64,int>>fm(C.n);map<u64,int>gm;for(int i=0;i<C.n;i++){for(auto[q,e]:fac(C.P[i]-1))fm[i][q]+=e;for(auto[q,e]:fac(C.P[i]+1))fm[i][q]+=e;auto it=fm[i].find(2);if(--it->second==0)fm[i].erase(it);for(auto[q,e]:fm[i])gm[q]=max(gm[q],e);}for(auto[q,e]:gm){BI z{q,e,vector<u64>(e+1,1)};for(int k=1;k<=e;k++)z.pw[k]=z.pw[k-1]*q;C.bs.push_back(move(z));}C.B=C.bs.size();unordered_map<u64,int>id;for(int b=0;b<C.B;b++)id[C.bs[b].q]=b;vector<int>ord(C.B);iota(ord.begin(),ord.end(),0);sort(ord.begin(),ord.end(),[&](int a,int b){u64 x=C.bs[a].pw[C.bs[a].maxe],y=C.bs[b].pw[C.bs[b].maxe];return x!=y?x>y:C.bs[a].q>C.bs[b].q;});vector<int>rank(C.B);for(int r=0;r<C.B;r++)rank[ord[r]]=r;C.F.resize(C.n);for(int i=0;i<C.n;i++){for(auto[q,e]:fm[i]){int b=id[q];C.F[i].push_back({rank[b],b,(uint8_t)e});}sort(C.F[i].begin(),C.F[i].end(),[](auto&a,auto&b){return a.rank<b.rank;});}C.inv.resize(C.B);for(int b=0;b<C.B;b++){C.inv[b].resize(C.bs[b].maxe+1);for(int e=1;e<=C.bs[b].maxe;e++){u64 m=C.bs[b].pw[e];C.inv[b][e].resize(C.n);for(int i=0;i<C.n;i++)C.inv[b][e][i]=invmod((C.P[i]%m).convert_to<u64>(),m);}}
 vector<uint512_t>max6(C.n),max5(C.n);for(int i=5;i<C.n;i++)max6[i]=uint512_t(C.P[i])*prodBelow(C,i,5);for(int i=4;i<C.n;i++)max5[i]=uint512_t(C.P[i])*prodBelow(C,i,4);
 unsigned long long tri=0,s3=0,vt=0,s4=0,wt=0,s5=0;auto stime=chrono::steady_clock::now();omp_set_num_threads(th);
 #pragma omp parallel for schedule(dynamic,1) reduction(+:tri,s3,vt,s4,wt,s5)
 for(int u=U0;u<=U1;u++){uint512_t B6=prodBelow(C,u,6);T3C state[64];for(int t=u+1;t<C.n-1;t++)for(int j=t+1;j<C.n;j++){tri++;int ns;uint512_t x3,M3;if(!crtT3(C,j,t,u,B6,state,ns,x3,M3))continue;s3++;int v0=max(5,(int)(lower_bound(max6.begin()+5,max6.begin()+u,x3)-max6.begin()));for(int v=v0;v<u;v++){vt++;uint512_t B5=prodBelow(C,v,5),x4,M4;if(!crt4from3(C,j,t,u,v,state,ns,B5,x4,M4))continue;s4++;int w0=max(4,(int)(lower_bound(max5.begin()+4,max5.begin()+v,x4)-max5.begin()));for(int w=w0;w<v;w++){wt++;uint512_t B4=prodBelow(C,w,4),x5,M5;int top[5]={j,t,u,v,w};if(!crtH(C,top,5,B4,x5,M5))continue;s5++;
#pragma omp critical
 {cerr<<"TOP5 "<<j<<","<<t<<","<<u<<","<<v<<","<<w<<"\n";}}}}}
 double sec=chrono::duration<double>(chrono::steady_clock::now()-stime).count();cerr<<"DONE triples="<<tri<<" s3="<<s3<<" vtests="<<vt<<" s4="<<s4<<" wtests="<<wt<<" s5="<<s5<<" sec="<<sec<<"\n";return 2;}
