#include <bits/stdc++.h>
using namespace std;
static constexpr int CMAX=23;
struct O{array<uint64_t,3>b{};array<uint16_t,CMAX>c{};};
struct B{vector<int>col;vector<O>o;};
struct P{array<uint16_t,CMAX>c{};uint16_t a=0,b=0;};
struct H{uint64_t r=0;array<uint16_t,4>i{};bool operator<(H const&z)const{return r<z.r;}};
static inline array<uint16_t,CMAX> addc(auto const&a,auto const&b,auto const&m){array<uint16_t,CMAX>z{};for(int i=0;i<CMAX;i++){unsigned v=(unsigned)a[i]+b[i];if(v>=m[i])v-=m[i];z[i]=(uint16_t)v;}return z;}
static uint64_t enc(auto const&a,vector<int>const&ix,auto const&m){uint64_t z=0,p=1;for(int j:ix){z+=p*a[j];p*=m[j];}return z;}
static uint64_t ord(vector<int>const&ix,auto const&m){uint64_t p=1;for(int j:ix)p*=m[j];return p;}
static uint64_t sub(uint64_t a,uint64_t b,vector<int>const&ix,auto const&m){uint64_t z=0,p=1;for(int j:ix){int q=m[j],x=a%q,y=b%q,d=x-y;if(d<0)d+=q;z+=p*d;p*=q;a/=q;b/=q;}return z;}
static vector<P> pairs(B const&a,B const&b,auto const&m){vector<P>v;v.reserve(a.o.size()*b.o.size());for(int i=0;i<(int)a.o.size();i++)for(int j=0;j<(int)b.o.size();j++)v.push_back({addc(a.o[i].c,b.o[j].c,m),(uint16_t)i,(uint16_t)j});return v;}
struct BK{vector<int>ofs,ids;vector<uint32_t>pc;};
static BK bucket(vector<P>const&v,vector<int>const&pre,auto const&m){uint64_t bc64=ord(pre,m);if(bc64>200000000ULL)throw runtime_error("b");int bc=(int)bc64;BK z;z.ofs.assign(bc+1,0);z.ids.resize(v.size());z.pc.resize(v.size());for(int i=0;i<(int)v.size();i++){uint32_t c=(uint32_t)enc(v[i].c,pre,m);z.pc[i]=c;z.ofs[c+1]++;}for(int i=0;i<bc;i++)z.ofs[i+1]+=z.ofs[i];vector<int>pos=z.ofs;for(int i=0;i<(int)v.size();i++)z.ids[pos[z.pc[i]]++]=i;return z;}
static vector<H> merge2(vector<P>const&A,vector<P>const&Bv,BK const&bb,vector<uint32_t>const&ap,vector<int>const&pre,vector<int>const&rem,uint64_t goal,auto const&m){vector<H>out;long double ex=(long double)A.size()*Bv.size()/bb.ofs.size();out.reserve((size_t)(ex*1.10+1000));for(int ai=0;ai<(int)A.size();ai++){auto&a=A[ai];uint64_t need=sub(goal,ap[ai],pre,m);for(int p=bb.ofs[need];p<bb.ofs[need+1];p++){auto&b=Bv[bb.ids[p]];auto c=addc(a.c,b.c,m);out.push_back({enc(c,rem,m),{a.a,a.b,b.a,b.b}});}}return out;}
static int vp5(long long d,int E){int e=0;long long m=5;for(;e<E;e++,m*=5)if(d%m)return e;return E;}
int main(int ac,char**av){
 if(ac!=14)return 1;string zp=av[1],fp=av[2],op=av[5];int slot=stoi(av[3]),slots=stoi(av[4]);if(slot<0||slots<1||slot>=slots)return 2;const int f1=14,f2=6;
 ifstream in(zp,ios::binary);uint32_t R,N;in.read((char*)&R,4);in.read((char*)&N,4);if(R!=57||N!=1029)return 3;vector<uint32_t>q(R);in.read((char*)q.data(),4*R);vector<uint16_t>A((size_t)R*N);in.read((char*)A.data(),2*A.size());vector<uint8_t>x0(N);in.read((char*)x0.data(),N);if(!in)return 4;
 ifstream qi(fp,ios::binary);uint32_t K,N5;qi.read((char*)&K,4);qi.read((char*)&N5,4);if(K!=29||N5!=N)return 5;vector<uint32_t>q5(K),t5(K);vector<vector<uint16_t>>a5(K,vector<uint16_t>(N));for(int r=0;r<(int)K;r++){qi.read((char*)&q5[r],4);qi.read((char*)&t5[r],4);qi.read((char*)a5[r].data(),2*N);}if(!qi||q5[0]!=625||t5[0]||q5[f1]%5||q5[f2]%5)return 6;
 vector<int>cr,ce;array<uint16_t,CMAX>mod{};for(int r=0;r<(int)R;r++)if(q[r]>3){int m=q[r]/3,e=0,z=m;while(z>1){if(z%3)return 7;z/=3;e++;}cr.push_back(r);ce.push_back(e);mod[cr.size()-1]=m;}if(cr.size()!=20||accumulate(ce.begin(),ce.end(),0)!=35)return 8;mod[20]=625;mod[21]=mod[22]=5;
 vector<B>bs(8);vector<int>cover(N);for(int k=0;k<8;k++){ifstream f(av[6+k],ios::binary);uint32_t mg,id,nb,no,dd;f.read((char*)&mg,4);f.read((char*)&id,4);f.read((char*)&nb,4);f.read((char*)&no,4);f.read((char*)&dd,4);if(mg!=0x62336231||id!=(uint32_t)k||dd!=35)return 9;bs[k].col.resize(nb);for(int j=0;j<(int)nb;j++){uint16_t z;f.read((char*)&z,2);bs[k].col[j]=z;if(z>=N||cover[z]++)return 10;}bs[k].o.resize(no);for(auto&o:bs[k].o){f.read((char*)o.b.data(),24);array<uint8_t,35>d{};f.read((char*)d.data(),35);int di=0;for(int ci=0;ci<20;ci++){int mul=1,v=0;for(int z=0;z<ce[ci];z++){if(di>=35||d[di]>2)return 11;v+=mul*d[di++];mul*=3;}o.c[ci]=v;}if(di!=35)return 12;unsigned s0=0,s1=0,s2=0;for(int j=0;j<(int)nb;j++)if((o.b[j>>6]>>(j&63))&1ULL){int x=bs[k].col[j];s0+=a5[0][x];s1+=a5[f1][x];s2+=a5[f2][x];}o.c[20]=s0%625;o.c[21]=s1%5;o.c[22]=s2%5;}if(!f)return 13;}for(int z:cover)if(z!=1)return 14;
 array<uint16_t,CMAX>tar{};for(int ci=0;ci<20;ci++){int r=cr[ci];long long s=0;for(int i=0;i<(int)N;i++)if(x0[i])s+=A[(size_t)r*N+i];if(s%3)return 15;int m=mod[ci];long long z=(-(s/3))%m;if(z<0)z+=m;tar[ci]=z;}tar[20]=0;tar[21]=t5[f1]%5;tar[22]=t5[f2]%5;
 long long dp[11];fill(begin(dp),end(dp),-1);dp[0]=0;for(int j=0;j<20;j++)for(int s=10-ce[j];s>=0;s--)if(dp[s]>=0&&dp[s+ce[j]]<0)dp[s+ce[j]]=dp[s]|(1LL<<j);if(dp[10]<0)return 16;vector<int>pre,rem;for(int j=0;j<20;j++)if(dp[10]>>j&1)pre.push_back(j);vector<char>used(CMAX);for(int j:pre)used[j]=1;for(int j=0;j<CMAX;j++)if(!used[j])rem.push_back(j);uint64_t po=ord(pre,mod);if(po!=59049)return 17;
 vector<P>p[4];for(int k=0;k<4;k++)p[k]=pairs(bs[2*k],bs[2*k+1],mod);BK b1=bucket(p[1],pre,mod),b3=bucket(p[3],pre,mod);vector<uint32_t>p0c(p[0].size()),p2c(p[2].size());for(int i=0;i<(int)p[0].size();i++)p0c[i]=enc(p[0][i].c,pre,mod);for(int i=0;i<(int)p[2].size();i++)p2c[i]=enc(p[2][i].c,pre,mod);
 uint64_t tp=enc(tar,pre,mod),tr=enc(tar,rem,mod);long long nh=0,no=0,done=0;int best=-1,bex=-1,bw=-1;array<uint16_t,8>bc{};vector<int>bl;
 auto emit=[&](){ofstream out(op);out<<"slot="<<slot<<"\nslots="<<slots<<"\ndone="<<done<<"\nhits="<<nh<<"\nodd="<<no<<"\nbest="<<best<<"\nexact="<<bex<<"\nweight="<<bw<<"\nchoices=";for(int k=0;k<8;k++)out<<(k?",":"")<<bc[k];out<<"\nlevels=";for(int r=0;r<(int)bl.size();r++)out<<(r?",":"")<<bl[r];out<<"\n";};
 auto eval=[&](array<uint16_t,8>const&s){vector<uint8_t>x(N);for(int k=0;k<8;k++){auto&o=bs[k].o[s[k]];for(int j=0;j<(int)bs[k].col.size();j++)x[bs[k].col[j]]=(o.b[j>>6]>>(j&63))&1ULL;}int wt=accumulate(x.begin(),x.end(),0);nh++;if(!(wt&1))return;no++;vector<int>lev(K);int sd=0,ex=0;for(int r=0;r<(int)K;r++){long long v=0;for(int i=0;i<(int)N;i++)if(x[i])v+=a5[r][i];int E=0;for(uint32_t z=q5[r];z>1;z/=5)E++;lev[r]=vp5(v-(long long)t5[r],E);sd+=lev[r];if(lev[r]==E)ex++;}if(lev[f1]<1||lev[f2]<1)abort();if(sd>best||(sd==best&&ex>bex)){best=sd;bex=ex;bw=wt;bc=s;bl=lev;emit();}};
 emit();for(uint64_t rp=slot;rp<po;rp+=slots){uint64_t rp2=sub(tp,rp,pre,mod);auto L=merge2(p[0],p[1],b1,p0c,pre,rem,rp,mod),Q=merge2(p[2],p[3],b3,p2c,pre,rem,rp2,mod);sort(Q.begin(),Q.end());for(auto&u:L){uint64_t need=sub(tr,u.r,rem,mod);auto lo=lower_bound(Q.begin(),Q.end(),H{need,{}});for(auto it=lo;it!=Q.end()&&it->r==need;++it){array<uint16_t,8>s{};for(int z=0;z<4;z++)s[z]=u.i[z];for(int z=0;z<4;z++)s[4+z]=it->i[z];eval(s);}}done++;if((done&15)==0)emit();}emit();return 0;
}
