#include <bits/stdc++.h>
using namespace std;
static constexpr int CMAX=22;
struct Opt { array<uint64_t,3> bits{}; array<uint16_t,CMAX> c{}; };
struct Block { vector<int> col; vector<Opt> o; };
struct Pair { array<uint16_t,CMAX> c{}; uint16_t a=0,b=0; };
struct Hit { uint64_t rem=0; array<uint16_t,4> i{}; bool operator<(Hit const& z)const{return rem<z.rem;} };
static inline array<uint16_t,CMAX> addc(const array<uint16_t,CMAX>&a,const array<uint16_t,CMAX>&b,const array<uint16_t,CMAX>&mod){array<uint16_t,CMAX> z{};for(int i=0;i<CMAX;i++){unsigned v=(unsigned)a[i]+b[i];if(v>=mod[i])v-=mod[i];z[i]=(uint16_t)v;}return z;}
static uint64_t enc(const array<uint16_t,CMAX>&a,const vector<int>&ix,const array<uint16_t,CMAX>&mod){uint64_t z=0,p=1;for(int j:ix){z+=p*a[j];p*=mod[j];}return z;}
static uint64_t ord(const vector<int>&ix,const array<uint16_t,CMAX>&mod){uint64_t p=1;for(int j:ix)p*=mod[j];return p;}
static uint64_t subcode(uint64_t a,uint64_t b,const vector<int>&ix,const array<uint16_t,CMAX>&mod){uint64_t z=0,p=1;for(int j:ix){int m=mod[j],x=a%m,y=b%m,d=x-y;if(d<0)d+=m;z+=p*d;p*=m;a/=m;b/=m;}return z;}
static vector<Pair> pairlist(const Block&a,const Block&b,const array<uint16_t,CMAX>&mod){vector<Pair>v;v.reserve(a.o.size()*b.o.size());for(int i=0;i<(int)a.o.size();i++)for(int j=0;j<(int)b.o.size();j++)v.push_back({addc(a.o[i].c,b.o[j].c,mod),(uint16_t)i,(uint16_t)j});return v;}
static vector<Hit> merge2(const vector<Pair>&A,const vector<Pair>&B,const vector<int>&pre,const vector<int>&rem,uint64_t goal,const array<uint16_t,CMAX>&mod){uint64_t bc64=ord(pre,mod);if(bc64>200000000ULL)throw runtime_error("bucket");int bc=(int)bc64;vector<int>cnt(bc),ofs(bc+1),ids(B.size());for(auto&x:B)cnt[enc(x.c,pre,mod)]++;for(int i=0;i<bc;i++)ofs[i+1]=ofs[i]+cnt[i];vector<int>pos=ofs;for(int i=0;i<(int)B.size();i++)ids[pos[enc(B[i].c,pre,mod)]++]=i;long double expect=(long double)A.size()*B.size()/bc;vector<Hit>out;out.reserve((size_t)(expect*1.08+1000));for(auto&a:A){uint64_t need=subcode(goal,enc(a.c,pre,mod),pre,mod);for(int pp=ofs[need];pp<ofs[need+1];pp++){auto&b=B[ids[pp]];auto c=addc(a.c,b.c,mod);out.push_back({enc(c,rem,mod),{a.a,a.b,b.a,b.b}});}}return out;}
static int vp5(long long d,int E){int e=0;long long m=5;for(;e<E;e++,m*=5)if(d%m)return e;return E;}
int main(int ac,char**av){
 if(ac!=15){cerr<<"usage z q5 seed tries force out b0..b7\n";return 1;}
 string zpath=av[1],qpath=av[2],outp=av[6];uint64_t seed=stoull(av[3]);int tries=stoi(av[4]),fr=stoi(av[5]);
 ifstream in(zpath,ios::binary);uint32_t R,N;in.read((char*)&R,4);in.read((char*)&N,4);if(R!=57||N!=1029)return 2;vector<uint32_t>q(R);in.read((char*)q.data(),4*R);vector<uint16_t>A((size_t)R*N);in.read((char*)A.data(),2*A.size());vector<uint8_t>x0(N);in.read((char*)x0.data(),N);if(!in)return 3;
 ifstream qi(qpath,ios::binary);uint32_t K,N5;qi.read((char*)&K,4);qi.read((char*)&N5,4);if(K!=29||N5!=N||fr<=0||fr>=(int)K)return 4;vector<uint32_t>q5(K),t5(K);vector<vector<uint16_t>>a5(K,vector<uint16_t>(N));for(int r=0;r<(int)K;r++){qi.read((char*)&q5[r],4);qi.read((char*)&t5[r],4);qi.read((char*)a5[r].data(),2*N);}if(!qi||q5[0]!=625||t5[0]!=0||q5[fr]%5)return 5;
 vector<int>crow,cexp;array<uint16_t,CMAX>mod{};for(int r=0;r<(int)R;r++)if(q[r]>3){int m=q[r]/3,e=0,z=m;while(z>1){if(z%3)return 6;z/=3;e++;}crow.push_back(r);cexp.push_back(e);mod[crow.size()-1]=m;}if(crow.size()!=20||accumulate(cexp.begin(),cexp.end(),0)!=35)return 7;mod[20]=625;mod[21]=5;
 vector<Block>bs(8);vector<int>cover(N);for(int k=0;k<8;k++){ifstream f(av[7+k],ios::binary);uint32_t mg,id,nb,no,dd;f.read((char*)&mg,4);f.read((char*)&id,4);f.read((char*)&nb,4);f.read((char*)&no,4);f.read((char*)&dd,4);if(mg!=0x62336231||id!=(uint32_t)k||dd!=35)return 8;bs[k].col.resize(nb);for(int j=0;j<(int)nb;j++){uint16_t z;f.read((char*)&z,2);bs[k].col[j]=z;if(z>=N||cover[z]++)return 9;}bs[k].o.resize(no);for(auto&o:bs[k].o){f.read((char*)o.bits.data(),24);array<uint8_t,35>d{};f.read((char*)d.data(),35);int di=0;for(int ci=0;ci<20;ci++){int mul=1,v=0;for(int z=0;z<cexp[ci];z++){if(d[di]>2)return 10;v+=mul*d[di++];mul*=3;}o.c[ci]=v;}if(di!=35)return 11;unsigned s0=0,s1=0;for(int j=0;j<(int)nb;j++)if((o.bits[j>>6]>>(j&63))&1ULL){s0+=a5[0][bs[k].col[j]];s1+=a5[fr][bs[k].col[j]];}o.c[20]=s0%625;o.c[21]=s1%5;}if(!f)return 12;}
 for(int z:cover)if(z!=1)return 13;
 array<uint16_t,CMAX>target{};for(int ci=0;ci<20;ci++){int r=crow[ci];long long s=0;for(int i=0;i<(int)N;i++)if(x0[i])s+=A[(size_t)r*N+i];if(s%3)return 14;int m=mod[ci];long long z=(-(s/3))%m;if(z<0)z+=m;target[ci]=z;}target[20]=0;target[21]=t5[fr]%5;
 vector<Pair>p[4];for(int k=0;k<4;k++)p[k]=pairlist(bs[2*k],bs[2*k+1],mod);
 mt19937_64 rng(seed^0x62577239ULL^((uint64_t)fr<<40));vector<int>base(20);iota(base.begin(),base.end(),0);long long nhit=0,nodd=0;int best=-1,bestExact=-1,bestWeight=-1;array<uint16_t,8>bestc{};vector<int>bestLev;
 auto eval=[&](array<uint16_t,8> const&sol){vector<uint8_t>x(N);for(int k=0;k<8;k++){auto&o=bs[k].o[sol[k]];for(int j=0;j<(int)bs[k].col.size();j++)x[bs[k].col[j]]=(o.bits[j>>6]>>(j&63))&1ULL;}int wt=accumulate(x.begin(),x.end(),0);nhit++;if(!(wt&1))return;nodd++;vector<int>lev(K);int sd=0,ex=0;for(int r=0;r<(int)K;r++){long long s=0;for(int i=0;i<(int)N;i++)if(x[i])s+=a5[r][i];long long d=s-(long long)t5[r];int E=0;for(uint32_t z=q5[r];z>1;z/=5)E++;lev[r]=vp5(d,E);sd+=lev[r];if(lev[r]==E)ex++;}if(lev[fr]<1){cerr<<"forcefail\n";abort();}if(sd>best||(sd==best&&ex>bestExact)){best=sd;bestExact=ex;bestWeight=wt;bestc=sol;bestLev=lev;cerr<<"BEST digits="<<best<<" exact="<<bestExact<<" weight="<<wt<<" hits="<<nhit<<" odd="<<nodd<<"\n";}};
 auto start=chrono::steady_clock::now();
 for(int at=0;at<tries;at++){shuffle(base.begin(),base.end(),rng);vector<int>pre,rem;int d=0;for(int j:base)if(d+cexp[j]<=10){pre.push_back(j);d+=cexp[j];}if(d!=10)return 15;vector<char>used(CMAX);for(int j:pre)used[j]=1;for(int j=0;j<CMAX;j++)if(!used[j])rem.push_back(j);uint64_t tp=enc(target,pre,mod),tr=enc(target,rem,mod),po=ord(pre,mod),rp=rng()%po,rp2=subcode(tp,rp,pre,mod);auto L=merge2(p[0],p[1],pre,rem,rp,mod);auto H=merge2(p[2],p[3],pre,rem,rp2,mod);sort(H.begin(),H.end());for(auto&u:L){uint64_t need=subcode(tr,u.rem,rem,mod);auto lo=lower_bound(H.begin(),H.end(),Hit{need,{}});for(auto it=lo;it!=H.end()&&it->rem==need;++it){array<uint16_t,8>s{};for(int z=0;z<4;z++)s[z]=u.i[z];for(int z=0;z<4;z++)s[4+z]=it->i[z];eval(s);}}cerr<<"at="<<at<<" hits="<<nhit<<" odd="<<nodd<<" best="<<best<<" sec="<<chrono::duration<double>(chrono::steady_clock::now()-start).count()<<"\n";}
 ofstream out(outp);out<<"force="<<fr<<"\nhits="<<nhit<<"\nodd="<<nodd<<"\nbest="<<best<<"\nexact="<<bestExact<<"\nweight="<<bestWeight<<"\nchoices=";for(int k=0;k<8;k++)out<<(k?",":"")<<bestc[k];out<<"\nlevels=";for(int r=0;r<(int)bestLev.size();r++)out<<(r?",":"")<<bestLev[r];out<<"\n";return best>=0?0:2;
}
