#include <bits/stdc++.h>
using namespace std;
static constexpr uint64_t MASK35=(1ULL<<35)-1;
struct O{array<uint64_t,3>bits{};uint64_t m1=0,m2=0;};
struct B{vector<int>col;vector<O>o;};
struct P{uint64_t m1,m2;uint16_t a,b;};
struct H{uint64_t rem;array<uint16_t,4>i;bool operator<(H const&z)const{return rem<z.rem;}};
static inline pair<uint64_t,uint64_t> addm(uint64_t a1,uint64_t a2,uint64_t b1,uint64_t b2){uint64_t a0=MASK35&~(a1|a2),b0=MASK35&~(b1|b2);uint64_t r1=(a0&b1)|(a1&b0)|(a2&b2);uint64_t r2=(a0&b2)|(a2&b0)|(a1&b1);return {r1,r2};}
static uint64_t enc(uint64_t m1,uint64_t m2,vector<int>const&c){uint64_t z=0,p=1;for(int j:c){int d=(m1>>j&1)?1:((m2>>j&1)?2:0);z+=p*d;p*=3;}return z;}
static uint64_t subcode(uint64_t a,uint64_t b,int n){uint64_t z=0,p=1;for(int j=0;j<n;j++){int x=a%3,y=b%3,d=x-y;if(d<0)d+=3;z+=p*d;p*=3;a/=3;b/=3;}return z;}
static pair<uint64_t,uint64_t> decmask(uint64_t code,vector<int>const&c){uint64_t m1=0,m2=0;for(int j:c){int d=code%3;code/=3;if(d==1)m1|=1ULL<<j;else if(d==2)m2|=1ULL<<j;}return {m1,m2};}
static vector<P> pairlist(B const&a,B const&b){vector<P>v;v.reserve(a.o.size()*b.o.size());for(int i=0;i<(int)a.o.size();i++)for(int j=0;j<(int)b.o.size();j++){auto [x,y]=addm(a.o[i].m1,a.o[i].m2,b.o[j].m1,b.o[j].m2);v.push_back({x,y,(uint16_t)i,(uint16_t)j});}return v;}
static vector<H> merge2(vector<P>const&A,vector<P>const&Bv,vector<int>const&pre,vector<int>const&rem,uint64_t goal){int bc=1;for(int z:pre)bc*=3;vector<int>cnt(bc),ofs(bc+1),ids(Bv.size());for(auto&x:Bv)cnt[enc(x.m1,x.m2,pre)]++;for(int i=0;i<bc;i++)ofs[i+1]=ofs[i]+cnt[i];vector<int>pos=ofs;for(int i=0;i<(int)Bv.size();i++)ids[pos[enc(Bv[i].m1,Bv[i].m2,pre)]++]=i;vector<H>out;double expect=(double)A.size()*Bv.size()/bc;out.reserve((size_t)(expect*1.15+100));for(auto&a:A){uint64_t ap=enc(a.m1,a.m2,pre),need=subcode(goal,ap,pre.size());for(int pp=ofs[need];pp<ofs[need+1];pp++){auto&b=Bv[ids[pp]];auto [m1,m2]=addm(a.m1,a.m2,b.m1,b.m2);out.push_back({enc(m1,m2,rem),{a.a,a.b,b.a,b.b}});}}return out;}
int main(int ac,char**av){if(ac<13){cerr<<"usage data seed tries out b0..b7 [test]\n";return 1;}string data=av[1],outp=av[4];uint64_t seed=stoull(av[2]);int tries=stoi(av[3]);bool test=ac>13;
 ifstream in(data,ios::binary);uint32_t R,N;in.read((char*)&R,4);in.read((char*)&N,4);vector<uint32_t>q(R);in.read((char*)q.data(),4*R);vector<uint16_t>A((size_t)R*N);in.read((char*)A.data(),2*A.size());vector<uint8_t>x0(N);in.read((char*)x0.data(),N);if(R!=57||N!=1029||!in)return 2;
 vector<B>bs(8);vector<int>cover(N);
 for(int k=0;k<8;k++){ifstream f(av[5+k],ios::binary);uint32_t mg,id,nb,no,dd;f.read((char*)&mg,4);f.read((char*)&id,4);f.read((char*)&nb,4);f.read((char*)&no,4);f.read((char*)&dd,4);if(mg!=0x62336231||id!=(uint32_t)k||dd!=35)return 3;bs[k].col.resize(nb);for(int j=0;j<(int)nb;j++){uint16_t z;f.read((char*)&z,2);bs[k].col[j]=z;if(z>=N||cover[z]++)return 4;}bs[k].o.resize(no);for(auto&o:bs[k].o){f.read((char*)o.bits.data(),24);array<uint8_t,35>d{};f.read((char*)d.data(),35);for(int j=0;j<35;j++){if(d[j]==1)o.m1|=1ULL<<j;else if(d[j]==2)o.m2|=1ULL<<j;else if(d[j]>2)return 5;}}if(!f)return 6;cerr<<"b"<<k<<"="<<no<<" ";}cerr<<"\n";for(int z:cover)if(z!=1)return 7;
 uint64_t t1=0,t2=0;int di=0;for(int r=0;r<57;r++)if(q[r]>3){long long s=0;for(int i=0;i<(int)N;i++)if(x0[i])s+=A[(size_t)r*N+i];int mod=q[r]/3,z=(int)((-(s/3))%mod);if(z<0)z+=mod;while(mod>1){int d=z%3;if(d==1)t1|=1ULL<<di;else if(d==2)t2|=1ULL<<di;di++;z/=3;mod/=3;}}if(di!=35)return 8;
 vector<uint16_t>known(8,1);if(test){t1=t2=0;for(int k=0;k<8;k++){int z=min<int>(1,bs[k].o.size()-1);known[k]=z;auto w=addm(t1,t2,bs[k].o[z].m1,bs[k].o[z].m2);t1=w.first;t2=w.second;}cerr<<"TEST\n";}
 vector<P>p[4];for(int k=0;k<4;k++){p[k]=pairlist(bs[2*k],bs[2*k+1]);cerr<<"p"<<k<<"="<<p[k].size()<<" ";}cerr<<"\n";
 mt19937_64 rng(seed^0x77239f4aULL);vector<int>all(35);iota(all.begin(),all.end(),0);vector<uint16_t>sol;for(int at=0;at<tries&&!sol.size();at++){shuffle(all.begin(),all.end(),rng);int d=11;long long L=p[0].size();while(d<13){long double e=(long double)L*L/powl(3.0L,d);long double hit=e*e/powl(3.0L,35-d);if(hit>.25L)break;d++;}vector<int>pre(all.begin(),all.begin()+d),rem(all.begin()+d,all.end());uint64_t tp=enc(t1,t2,pre),tr=enc(t1,t2,rem);uint64_t rp=0;if(test){uint64_t a1=0,a2=0;for(int k=0;k<4;k++){auto w=addm(a1,a2,bs[k].o[known[k]].m1,bs[k].o[known[k]].m2);a1=w.first;a2=w.second;}rp=enc(a1,a2,pre);}else{uint64_t pw=1;for(int j=0;j<d;j++){int z=rng()%3;rp+=pw*z;pw*=3;}}uint64_t rp2=subcode(tp,rp,d);auto Lh=merge2(p[0],p[1],pre,rem,rp);auto Rh=merge2(p[2],p[3],pre,rem,rp2);sort(Rh.begin(),Rh.end());cerr<<"at="<<at<<" d="<<d<<" l="<<Lh.size()<<" r="<<Rh.size()<<"\n";for(auto&u:Lh){uint64_t need=subcode(tr,u.rem,rem.size());auto it=lower_bound(Rh.begin(),Rh.end(),H{need,{}});if(it!=Rh.end()&&it->rem==need){sol.assign(8,0);for(int z=0;z<4;z++)sol[z]=u.i[z];for(int z=0;z<4;z++)sol[4+z]=it->i[z];break;}}
 }
 if(sol.empty()){ofstream o(outp);o<<"OPEN\n";return 2;}vector<uint8_t>x(N);for(int k=0;k<8;k++){auto&o=bs[k].o[sol[k]];for(int j=0;j<(int)bs[k].col.size();j++)x[bs[k].col[j]]=(o.bits[j>>6]>>(j&63))&1;}
 uint64_t s1=0,s2=0;for(int k=0;k<8;k++){auto w=addm(s1,s2,bs[k].o[sol[k]].m1,bs[k].o[sol[k]].m2);s1=w.first;s2=w.second;}if(s1!=t1||s2!=t2){cerr<<"target fail\n";return 9;}
 if(!test)for(int r=0;r<57;r++){long long s=0;for(int i=0;i<(int)N;i++)if(x[i])s+=A[(size_t)r*N+i];if(s%q[r]){cerr<<"rowfail "<<r<<"/"<<q[r]<<" res="<<s%q[r]<<"\n";return 10;}}
 ofstream o(outp);o<<(test?"TEST_FOUND\n":"FOUND\n");o<<"choices=";for(int k=0;k<8;k++)o<<(k?",":"")<<sol[k];o<<"\nweight="<<accumulate(x.begin(),x.end(),0)<<"\nindices=";bool f=0;for(int i=0;i<(int)N;i++)if(x[i]){o<<(f?",":"")<<i;f=1;}o<<"\n";cerr<<"FOUND\n";return 0;}
