#include <bits/stdc++.h>
using namespace std;
static constexpr int CMAX=20;
struct O{array<uint64_t,3>bits{};array<uint16_t,CMAX> c{};};
struct B{vector<int>col;vector<O>o;};
struct P{array<uint16_t,CMAX> c{};uint16_t a=0,b=0;};
struct H{uint64_t rem=0;array<uint16_t,4>i{};bool operator<(H const&z)const{return rem<z.rem;}};
static inline array<uint16_t,CMAX> addc(array<uint16_t,CMAX> const&a,array<uint16_t,CMAX> const&b,array<uint16_t,CMAX> const&mod,int nc){array<uint16_t,CMAX> z{};for(int i=0;i<nc;i++){int v=(int)a[i]+b[i];if(v>=mod[i])v-=mod[i];z[i]=v;}return z;}
static uint64_t enc(array<uint16_t,CMAX> const&a,vector<int>const&ix,array<uint16_t,CMAX> const&mod){uint64_t z=0,p=1;for(int j:ix){z+=p*a[j];p*=mod[j];}return z;}
static uint64_t order(vector<int>const&ix,array<uint16_t,CMAX>const&mod){uint64_t p=1;for(int j:ix)p*=mod[j];return p;}
static uint64_t subcode(uint64_t a,uint64_t b,vector<int>const&ix,array<uint16_t,CMAX>const&mod){uint64_t z=0,p=1;for(int j:ix){int m=mod[j],x=a%m,y=b%m,d=x-y;if(d<0)d+=m;z+=p*d;p*=m;a/=m;b/=m;}return z;}
static vector<P> pairlist(B const&a,B const&b,array<uint16_t,CMAX>const&mod,int nc){vector<P>v;v.reserve(a.o.size()*b.o.size());for(int i=0;i<(int)a.o.size();i++)for(int j=0;j<(int)b.o.size();j++)v.push_back({addc(a.o[i].c,b.o[j].c,mod,nc),(uint16_t)i,(uint16_t)j});return v;}
static vector<H> merge2(vector<P>const&A,vector<P>const&Bv,vector<int>const&pre,vector<int>const&rem,uint64_t goal,array<uint16_t,CMAX>const&mod,int nc){uint64_t bc64=order(pre,mod);if(bc64>100000000ULL)throw runtime_error("bucket");int bc=(int)bc64;vector<int>cnt(bc),ofs(bc+1),ids(Bv.size());for(auto&x:Bv)cnt[enc(x.c,pre,mod)]++;for(int i=0;i<bc;i++)ofs[i+1]=ofs[i]+cnt[i];vector<int>pos=ofs;for(int i=0;i<(int)Bv.size();i++)ids[pos[enc(Bv[i].c,pre,mod)]++]=i;vector<H>out;long double expect=(long double)A.size()*Bv.size()/bc;out.reserve((size_t)(expect*1.15+100));for(auto&a:A){uint64_t ap=enc(a.c,pre,mod),need=subcode(goal,ap,pre,mod);for(int pp=ofs[need];pp<ofs[need+1];pp++){auto&b=Bv[ids[pp]];auto cc=addc(a.c,b.c,mod,nc);out.push_back({enc(cc,rem,mod),{a.a,a.b,b.a,b.b}});}}return out;}
int main(int ac,char**av){if(ac<13){cerr<<"usage data seed tries out b0..b7 [test]\n";return 1;}string data=av[1],outp=av[4];uint64_t seed=stoull(av[2]);int tries=stoi(av[3]);bool test=ac>13;
 ifstream in(data,ios::binary);uint32_t R,N;in.read((char*)&R,4);in.read((char*)&N,4);vector<uint32_t>q(R);in.read((char*)q.data(),4*R);vector<uint16_t>A((size_t)R*N);in.read((char*)A.data(),2*A.size());vector<uint8_t>x0(N);in.read((char*)x0.data(),N);if(R!=57||N!=1029||!in)return 2;
 vector<int>crow,cexp;array<uint16_t,CMAX>mod{};for(int r=0;r<(int)R;r++)if(q[r]>3){int m=q[r]/3,e=0,z=m;while(z>1){if(z%3)return 20;z/=3;e++;}if((int)crow.size()>=CMAX)return 21;crow.push_back(r);cexp.push_back(e);mod[crow.size()-1]=m;}int nc=crow.size();if(nc!=20||accumulate(cexp.begin(),cexp.end(),0)!=35)return 22;
 vector<B>bs(8);vector<int>cover(N);
 for(int k=0;k<8;k++){ifstream f(av[5+k],ios::binary);uint32_t mg,id,nb,no,dd;f.read((char*)&mg,4);f.read((char*)&id,4);f.read((char*)&nb,4);f.read((char*)&no,4);f.read((char*)&dd,4);if(mg!=0x62336231||id!=(uint32_t)k||dd!=35)return 3;bs[k].col.resize(nb);for(int j=0;j<(int)nb;j++){uint16_t z;f.read((char*)&z,2);bs[k].col[j]=z;if(z>=N||cover[z]++)return 4;}bs[k].o.resize(no);for(auto&o:bs[k].o){f.read((char*)o.bits.data(),24);array<uint8_t,35>d{};f.read((char*)d.data(),35);int di=0;for(int ci=0;ci<nc;ci++){int mul=1,v=0;for(int z=0;z<cexp[ci];z++){if(d[di]>2)return 5;v+=mul*d[di++];mul*=3;}o.c[ci]=v;}if(di!=35)return 23;}if(!f)return 6;cerr<<"b"<<k<<"="<<no<<" ";}cerr<<"\n";for(int z:cover)if(z!=1)return 7;
 array<uint16_t,CMAX>target{};for(int ci=0;ci<nc;ci++){int r=crow[ci];long long s=0;for(int i=0;i<(int)N;i++)if(x0[i])s+=A[(size_t)r*N+i];if(s%3)return 24;int m=mod[ci];long long z=(-(s/3))%m;if(z<0)z+=m;target[ci]=z;}
 vector<uint16_t>known(8,1);if(test){target.fill(0);for(int k=0;k<8;k++){int z=min<int>(1,bs[k].o.size()-1);known[k]=z;target=addc(target,bs[k].o[z].c,mod,nc);}cerr<<"TEST\n";}
 vector<P>p[4];for(int k=0;k<4;k++){p[k]=pairlist(bs[2*k],bs[2*k+1],mod,nc);cerr<<"p"<<k<<"="<<p[k].size()<<" ";}cerr<<"\n";
 mt19937_64 rng(seed^0x77239f4aULL);vector<int>all(nc);iota(all.begin(),all.end(),0);vector<uint16_t>sol;
 for(int at=0;at<tries&&sol.empty();at++){shuffle(all.begin(),all.end(),rng);vector<int>pre,rem;int d=0;for(int j:all){if(d<11){pre.push_back(j);d+=cexp[j];}else rem.push_back(j);}if(pre.empty()||rem.empty())return 25;uint64_t tp=enc(target,pre,mod),tr=enc(target,rem,mod),po=order(pre,mod),rp;if(test){auto z=addc(addc(bs[0].o[known[0]].c,bs[1].o[known[1]].c,mod,nc),addc(bs[2].o[known[2]].c,bs[3].o[known[3]].c,mod,nc),mod,nc);rp=enc(z,pre,mod);}else rp=rng()%po;uint64_t rp2=subcode(tp,rp,pre,mod);auto Lh=merge2(p[0],p[1],pre,rem,rp,mod,nc);auto Rh=merge2(p[2],p[3],pre,rem,rp2,mod,nc);sort(Rh.begin(),Rh.end());cerr<<"at="<<at<<" d="<<d<<" l="<<Lh.size()<<" r="<<Rh.size()<<"\n";for(auto&u:Lh){uint64_t need=subcode(tr,u.rem,rem,mod);auto it=lower_bound(Rh.begin(),Rh.end(),H{need,{}});if(it!=Rh.end()&&it->rem==need){sol.assign(8,0);for(int z=0;z<4;z++)sol[z]=u.i[z];for(int z=0;z<4;z++)sol[4+z]=it->i[z];break;}}}
 if(sol.empty()){ofstream o(outp);o<<"OPEN\n";return 2;}vector<uint8_t>x(N);for(int k=0;k<8;k++){auto&o=bs[k].o[sol[k]];for(int j=0;j<(int)bs[k].col.size();j++)x[bs[k].col[j]]=(o.bits[j>>6]>>(j&63))&1;}
 array<uint16_t,CMAX>ss{};for(int k=0;k<8;k++)ss=addc(ss,bs[k].o[sol[k]].c,mod,nc);if(ss!=target)return 9;
 if(!test)for(int r=0;r<57;r++){long long s=0;for(int i=0;i<(int)N;i++)if(x[i])s+=A[(size_t)r*N+i];if(s%q[r]){cerr<<"rowfail "<<r<<"/"<<q[r]<<" res="<<s%q[r]<<"\n";return 10;}}
 ofstream o(outp);o<<(test?"TEST_FOUND\n":"FOUND\n");o<<"choices=";for(int k=0;k<8;k++)o<<(k?",":"")<<sol[k];o<<"\nweight="<<accumulate(x.begin(),x.end(),0)<<"\nindices=";bool ff=0;for(int i=0;i<(int)N;i++)if(x[i]){o<<(ff?",":"")<<i;ff=1;}o<<"\n";cerr<<"FOUND\n";return 0;}
