name: q63-stop
on:
  push:
    branches: [monalisa-tsp-search-2026-09-03]
    paths:
      - '.github/workflows/q63-stop.yml'
concurrency:
  group: q63-1
  cancel-in-progress: true
jobs:
  stop:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: ':'
